EWPP-1901: Update registration button information at the exact time.
openeuropa/oe_theme pull request #1026
Opened 2022-02-04 14:15 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-02-14 10:58 UTC, imanoleguskiza requested changes, later dismissed

2022-02-14 10:58 UTC, imanoleguskiza commented on modules/oe_theme_content_event/js/event_registration.js
> +   * Shows related information when registration is active.
Maybe something like: Shows registration information when the registration period is open.

2022-02-14 10:58 UTC, imanoleguskiza commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/InfoDisclosureExtraFieldBase.php
Can we improve the method description for isCurrentDay? Maybe something like: Asserts if a given timestamp corresponds to the same day of the current request time.

2022-02-14 10:58 UTC, imanoleguskiza commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/OnlineDisplayExtraFieldBase.php
> + * Base class for fields that require display livestream link in exact time.
Maybe: Base class for fields rendering livestream information.

2022-02-14 10:58 UTC, imanoleguskiza commented on modules/oe_theme_content_event/oe_theme_content_event.module
> +        'approaching_time' => FALSE,
This name is a bit confusing. How about we call it "registration_day" and "registration_day_description"?

2022-02-16 13:51 UTC, 22Alexandra requested changes

2022-02-16 13:51 UTC, 22Alexandra commented on modules/oe_theme_content_event/tests/src/FunctionalJavascript/InfoDisclosureExtraFieldTest.php
> +   * Tests that Event Online and Registration link are appeared exactly on time.
```suggestion
   * Tests that Event Online and Registration links are displayed exactly on time.
```

2022-02-16 13:51 UTC, 22Alexandra commented on modules/oe_theme_content_event/tests/src/FunctionalJavascript/InfoDisclosureExtraFieldTest.php
>      $livetime_elements = $this->getSession()->getPage()->findAll('css', '[data-livestream-element]');
```suggestion
    $livestream_elements = $this->getSession()->getPage()->findAll('css', '[data-livestream-element]');
```

2022-02-16 13:51 UTC, 22Alexandra commented on modules/oe_theme_content_event/tests/src/FunctionalJavascript/InfoDisclosureExtraFieldTest.php
> +    // Set start datetime in 10 minutes later.
```suggestion
    // Set start datetime 10 minutes later.
```

2022-02-16 18:51 UTC, 22Alexandra submitted a review, later dismissed

2022-03-25 07:51 UTC, 22Alexandra approved these changes

2022-03-25 12:58 UTC, upchuk approved these changes
Blind for imanol

2022-03-25 12:59 UTC, merged