EWPP-2016: Improve display of person teaser.
openeuropa/oe_theme pull request #1051
Opened 2022-03-01 13:11 UTC by imanoleguskiza

## EWPP-2016

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-03-07 19:34 UTC, sergepavle commented on modules/oe_theme_content_person/oe_theme_content_person.module
> +function oe_theme_content_person_theme() {
```suggestion
function oe_theme_content_person_theme(): array {
```

2022-03-15 07:59 UTC, sergepavle submitted a review, later dismissed

2022-03-23 11:02 UTC, 22Alexandra requested changes
This request from the ticket is missing: `Point 1. 2. and 3. should apply to all instances of the content item pattern, not only on person teaser.`

So we need to hide the contact name everywhere we render contacts and separate departments by comma instead of pipe too.

2022-03-23 11:02 UTC, 22Alexandra commented on templates/field/field--node--oe-departments--oe-person--teaser.html.twig
> +{%- include 'field--multiple-values--comma-separated.html.twig' -%}
This change has to be done for all the departments fields according to the ticket.

2022-03-30 07:44 UTC, 22Alexandra approved these changes, later dismissed

2022-03-31 13:54 UTC, yenyasinn commented on composer.json
> +        "phpmd/phpmd": "2.11.1"
Do we still need it? If not, can be removed before merge.

2022-03-31 13:54 UTC, yenyasinn submitted a review, later dismissed

2022-04-01 08:47 UTC, yenyasinn submitted a review, later dismissed

2022-04-06 13:20 UTC, yenyasinn approved these changes

2022-04-06 13:21 UTC, 22Alexandra approved these changes

2022-04-06 13:22 UTC, merged