EWPP-2023: Copyright and caption on Video media.
openeuropa/oe_theme pull request #1056
Opened 2022-03-04 16:28 UTC by yenyasinn

2022-03-09 12:28 UTC, upchuk requested changes, later dismissed

2022-03-09 12:28 UTC, upchuk commented on templates/field/field--media--oe-media-oembed-video.html.twig
> + * Theme override for remote video field on media items.
Why did you remove the "the"?

2022-03-10 12:47 UTC, 22Alexandra submitted a review, later dismissed

2022-03-25 16:25 UTC, nagyad submitted a review, later dismissed

2022-04-06 15:44 UTC, 22Alexandra approved these changes

2022-04-06 15:51 UTC, nagyad approved these changes

2022-04-06 16:03 UTC, merged