EWPP-2072: Update link fields to render external icon.
openeuropa/oe_theme pull request #1074
Opened 2022-04-03 12:49 UTC by 22Alexandra

2022-04-20 09:29 UTC, sergepavle commented on tests/src/Functional/ContentPersonRenderTest.php
> +    $second_link_icon = $transparency_links_items[0]->find('css', 'a.ecl-link svg.ecl-icon.ecl-icon--s.ecl-icon--primary.ecl-link__icon');
Are we checking again same link?
```suggestion
    $second_link_icon = $transparency_links_items[1]->find('css', 'a.ecl-link svg.ecl-icon.ecl-icon--s.ecl-icon--primary.ecl-link__icon');
```

2022-05-02 07:16 UTC, sergepavle approved these changes

2022-05-12 07:56 UTC, sergepavle approved these changes, later dismissed

2022-05-16 14:04 UTC, imanoleguskiza requested changes, later dismissed
We are missing a link in oe-theme-content-event-livestream.html.twig

2022-05-17 11:43 UTC, sergepavle approved these changes

2022-05-17 13:43 UTC, imanoleguskiza approved these changes

2022-05-17 13:43 UTC, merged