EWPP-2166: Fix access check for event programme items.
openeuropa/oe_theme pull request #1096
Opened 2022-05-12 15:41 UTC by nagyad

2022-05-13 09:25 UTC, 22Alexandra requested changes

2022-05-13 09:25 UTC, 22Alexandra commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/ProgrammeExtraField.php
> +      return [];
We shouldn't return empty array but use the `$isEmpty` flag of the `ExtraFieldDisplayFormattedBase`.

2022-05-13 16:12 UTC, 22Alexandra approved these changes, later dismissed

2022-06-21 06:53 UTC, 22Alexandra approved these changes

2022-06-21 06:55 UTC, upchuk approved these changes

2022-06-21 06:55 UTC, merged