EWPP-2320: Update to ECL 3.3.2.
openeuropa/oe_theme pull request #1118
Opened 2022-06-10 15:20 UTC by yenyasinn

2022-06-12 09:49 UTC, 22Alexandra submitted a review, later dismissed

2022-06-13 10:25 UTC, nagyad requested changes

2022-06-13 10:25 UTC, nagyad commented on modules/oe_theme_content_event/tests/src/FunctionalJavascript/InfoDisclosureExtraFieldTest.php
>      // Set livestream start date in 10 seconds later.
Comment should be updated as well.

2022-06-13 10:25 UTC, nagyad commented on modules/oe_theme_content_event/tests/src/FunctionalJavascript/InfoDisclosureExtraFieldTest.php
>        $this->assertTrue($livestream_element->isVisible());
Comment should be updated as well.

2022-06-13 13:46 UTC, nagyad approved these changes, later dismissed

2022-07-16 19:07 UTC, 22Alexandra approved these changes

2022-07-18 11:43 UTC, imanoleguskiza approved these changes
Approving for @nagyad

2022-07-18 11:47 UTC, merged