EPIC-EWPP-2022-External-links
openeuropa/oe_theme pull request #1119
Opened 2022-06-13 06:39 UTC by 22Alexandra

2022-06-17 08:45 UTC, ademarco requested changes, later dismissed

2022-06-17 08:45 UTC, ademarco commented on modules/oe_theme_helper/src/ExternalLinks.php
> +  public function isExternalLink($url): bool {
We should cover this with a dedicated test, where we throw at it all sorts of different values, of different types, and check the output.

2022-06-17 08:45 UTC, ademarco commented on modules/oe_theme_helper/src/ExternalLinks.php
> +    $internal_domain_expression = $this->configFactory->get('oe_theme_helper.internal_domains')->get('internal_domain');
We can get the expression in the constructor, as we really don't need the config factory for anything else in this service.

Let's have a property called $internalDomainExpression, and we simply fill it in in the constructor.

2022-06-21 15:30 UTC, imanoleguskiza approved these changes

2022-06-21 15:34 UTC, nagyad approved these changes

2022-06-21 15:49 UTC, merged