EWPP-2594: Use selenium 4.
openeuropa/oe_theme pull request #1161
Opened 2022-09-05 12:21 UTC by nagyad

2022-09-05 16:38 UTC, brummbar requested changes
It's important to determine the correct set of options now, as we will use this as baseline for OpenEuropa.

2022-09-05 16:38 UTC, brummbar commented on behat.yml.dist
> +        capabilities:
Let's start with the minimum set used by QA at https://webgate.ec.europa.eu/fpfis/qa/how-to?search=selenium:
```
capabilities:
  nativeEvents: true
  marionette: true
  browserName: chrome
```

2022-09-05 16:38 UTC, brummbar commented on phpunit.xml.dist
> +    <env name="MINK_DRIVER_ARGS_WEBDRIVER" value='["${selenium.browser}", {"browserName":"chrome","chromeOptions":{"w3c": false, "args":["--no-sandbox", "--start-maximized", "--disable-gpu", "--windo
Even Joinup here uses a very basic string:
```
MINK_DRIVER_ARGS_WEBDRIVER="['chrome', { 'chromeOptions': { 'w3c': false } }, 'http://localhost:4444/wd/hub']"
```
Let's start with that.

2022-09-06 07:48 UTC, brummbar approved these changes

2022-09-06 07:49 UTC, 22Alexandra approved these changes

2022-09-06 07:49 UTC, merged