EWPP-2558: Add table column sort support in CKEditor.
openeuropa/oe_theme pull request #1171
Opened 2022-09-30 08:57 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-10-04 14:17 UTC, nagyad requested changes

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +declare(strict_types=1);
Revert this change.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +        ->getAttribute('id'));
Make this one liner.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->click();
This can be reverted too.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->click();
This can be reverted too.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +        ->getAttribute('id'));
This can be reverted too.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +        ->getAttribute('id'));
Make this as one liner.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->click();
This can be one liner too.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->click();
Make these one liner.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
This can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-04 14:17 UTC, nagyad commented on modules/oe_theme_helper/tests/src/FunctionalJavascript/WysiwygTableTest.php
> +      ->pressButton('OK');
These can go in one line.

2022-10-06 08:56 UTC, nagyad approved these changes

2022-10-12 08:42 UTC, yenyasinn approved these changes

2022-10-12 12:02 UTC, merged