Ewpp 2559
openeuropa/oe_theme pull request #1172
Opened 2022-10-03 15:56 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-10-06 13:26 UTC, nagyad requested changes

2022-10-06 13:26 UTC, nagyad commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> +      // Add related to "Zebra striping" classes.
This sentence is not correct in English.

2022-10-06 13:26 UTC, nagyad commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> +          // Add related to "Sort" data attribute.
This sentence is not correct in English.

2022-10-06 14:04 UTC, sergepavle commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> +      // Add related to "Zebra striping" classes.
Fixed.

2022-10-06 14:04 UTC, sergepavle commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> +          // Add related to "Sort" data attribute.
Fixed.

2022-10-07 09:16 UTC, nagyad approved these changes, later dismissed

2022-10-12 08:43 UTC, yenyasinn submitted a review, later dismissed

2022-10-17 15:08 UTC, nagyad approved these changes

2022-10-17 15:08 UTC, yenyasinn approved these changes

2022-10-17 15:14 UTC, merged