EWPP-2646: Fix publication thumbnail translation render.
openeuropa/oe_theme pull request #1174
Opened 2022-10-04 15:15 UTC by nagyad

2022-10-07 16:52 UTC, sergepavle approved these changes

2022-10-07 17:13 UTC, sergepavle submitted a review, later dismissed

2022-10-11 06:59 UTC, 22Alexandra requested changes

2022-10-11 06:59 UTC, 22Alexandra commented on tests/src/Functional/ContentPublicationRenderTest.php
> +    \Drupal::service('content_translation.manager')->setEnabled('node', 'oe_publication', TRUE);
The bundle is already translatable because this is done in the `setUp()` method.

2022-10-11 06:59 UTC, 22Alexandra commented on tests/src/Functional/ContentPublicationRenderTest.php
> +  public function testPublicationThumbnailMediaTranslation(): void {
Why can't we test this in the previous test method? The title field is set to be translatable in the `setUp()` and then the translation of the node is being tested. We can just do all the configuration needed in the `setUp()` and then provide a `Thumbnail` for the publication node so we can test this scenario too.

2022-10-11 08:33 UTC, nagyad commented on tests/src/Functional/ContentPublicationRenderTest.php
> +  public function testPublicationThumbnailMediaTranslation(): void {
Because that method is over 400 lines. I don't like shovelling everything under one test case. Here we test a specific scenario and this scenario is separate for event as well.

2022-10-13 09:52 UTC, 22Alexandra submitted a review, later dismissed

2022-10-13 12:25 UTC, sergepavle approved these changes, later dismissed

2022-11-03 08:36 UTC, 22Alexandra approved these changes

2022-11-03 08:36 UTC, hernani approved these changes

2022-11-03 08:37 UTC, sergepavle approved these changes

2022-11-03 08:39 UTC, merged