EWPP-2506: Add classes to identify the last item per column.
openeuropa/oe_theme pull request #1191
Opened 2022-10-18 13:27 UTC by 22Alexandra

2022-10-20 16:41 UTC, sergepavle submitted a review, later dismissed

2022-10-21 08:37 UTC, nagyad submitted a review, later dismissed

2022-10-25 10:38 UTC, sergepavle approved these changes, later dismissed

2022-10-27 09:22 UTC, imanoleguskiza requested changes, later dismissed
Currently we are not using the tags display in link lists, we need to make sure we keep tthe same display as before.

2022-10-27 09:22 UTC, imanoleguskiza commented on templates/patterns/list_item/pattern-list-item.html.twig
> +    {# Always use the vertical variant of ECL Description list component for this pattern. #}
This comment is not very correct I would say. Shouldn't it be something like "Use the horizontal variant of ECL Description list component by default"?

2022-10-31 08:39 UTC, sergepavle approved these changes

2022-10-31 08:41 UTC, yenyasinn approved these changes

2022-10-31 08:41 UTC, nagyad approved these changes

2022-10-31 08:41 UTC, merged