EWPP-2718: Update ECL to 3.5.0 version.
openeuropa/oe_theme pull request #1192
Opened 2022-10-20 13:01 UTC by nagyad

2022-10-24 07:42 UTC, imanoleguskiza approved these changes, later dismissed

2022-10-24 10:35 UTC, 22Alexandra requested changes
We need to rename the patch files.

2022-10-25 06:21 UTC, 22Alexandra approved these changes, later dismissed

2022-10-27 07:07 UTC, 22Alexandra approved these changes, later dismissed

2022-10-27 07:47 UTC, upchuk requested changes
Please

2022-10-27 07:47 UTC, upchuk commented on composer.json
> +        "consolidation/annotated-command": "4.5.6",
Is this still needed?

2022-10-27 07:47 UTC, upchuk commented on tests/src/FunctionalJavascript/JavascriptBehavioursTest.php
> +      'Select all (4)',
Why is this happening? We cannot just change the test cause drone fails. There is a reason we have tests and that is to check if we break stuff. Not that if we break stuff, we just adapt the test. So please confirm what this is.

2022-10-27 08:40 UTC, upchuk approved these changes

2022-10-27 08:41 UTC, 22Alexandra approved these changes

2022-10-27 08:41 UTC, merged