EWPP-2734: Fix WysiwygTableTest with removing workaround.
openeuropa/oe_theme pull request #1210
Opened 2022-11-14 11:23 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-11-16 13:21 UTC, 22Alexandra requested changes

2022-11-16 13:21 UTC, 22Alexandra commented on tests/src/Behat/MinkContext.php
> +    $this->getSession()->wait(1000);
The scenario runs locally without the wait so maybe we should not add it because of drone and see why it fails in drone.

2022-11-16 18:04 UTC, sergepavle commented on tests/src/Behat/MinkContext.php
> +    $this->getSession()->wait(1000);
With using local docker I also can reproduce failure during the execution of behat tests `Scenario: The demo site navigation menu features dropdown menus`.
It is explicitly implemented delay on the show/hide of menu sub-items.

2022-11-17 07:03 UTC, 22Alexandra submitted a review, later dismissed

2022-11-24 16:40 UTC, yenyasinn submitted a review, later dismissed

2022-11-29 15:15 UTC, 22Alexandra approved these changes

2022-11-29 15:36 UTC, yenyasinn approved these changes

2022-11-29 15:38 UTC, merged