EWPP-2788: Add validation of path in \Drupal\oe_theme_helper\ExternalLinks::isExternalLink and update test coverage.
openeuropa/oe_theme pull request #1212
Opened 2022-11-17 15:44 UTC by sergepavle

…Links::isExternalLink and update test coverage.

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-11-18 13:57 UTC, nagyad requested changes

2022-11-18 13:57 UTC, nagyad commented on modules/oe_theme_helper/tests/src/Kernel/ExternalLinksTest.php
> +    $external_links->isExternalLink('randomschema://test');
I would add here some examples of drupal path like <front> or similar.

2022-11-21 09:17 UTC, nagyad approved these changes

2022-11-21 12:11 UTC, 22Alexandra approved these changes

2022-11-23 13:03 UTC, merged