Prepare release 3.0.0.
openeuropa/oe_theme pull request #1222
Opened 2022-12-05 16:19 UTC by imanoleguskiza

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-12-05 16:20 UTC, 22Alexandra approved these changes, later dismissed

2022-12-05 18:02 UTC, nagyad approved these changes

2022-12-05 18:03 UTC, nagyad requested changes
Changelog needs fix

2022-12-06 07:55 UTC, sergepavle approved these changes

2022-12-06 07:57 UTC, 22Alexandra approved these changes

2022-12-06 08:29 UTC, nagyad approved these changes

2022-12-06 08:53 UTC, merged