EWPP-2875: Add EC logo and remove the title from EC footers.
openeuropa/oe_theme pull request #1224
Opened 2022-12-07 12:36 UTC by 22Alexandra

2022-12-07 15:42 UTC, nagyad requested changes

2022-12-07 15:42 UTC, nagyad commented on oe_theme.theme
> +    }
Do we have this somewhere else? This resembles as pt-pt to me. Can we make this logic reusable if that is the case?

2022-12-07 15:42 UTC, nagyad commented on oe_theme.theme
> +      $ecl_logo = DRUPAL_ROOT . '/' . drupal_get_path('theme', 'oe_theme') . '/dist/' . $variables['ecl_component_library'] . '/images/logo/';
drupal_get_path is deprecated, let's use the service.

2022-12-07 15:42 UTC, nagyad commented on oe_theme.theme
> +  }
I see that we are executing the same code over the places. Please check if we can make a local helper function or a trait to reuse this logic.

2022-12-08 13:13 UTC, nagyad approved these changes, later dismissed

2022-12-12 09:47 UTC, nagyad submitted a review, later dismissed

2022-12-12 16:36 UTC, sergepavle approved these changes, later dismissed

2022-12-12 16:36 UTC, sergepavle commented on tests/src/Behat/OeThemeTestContext.php
>      // European Union footer is presented.
Currently, it is not anymore only the European Union footer.

2022-12-16 07:05 UTC, upchuk approved these changes
Blind

2022-12-16 07:08 UTC, yenyasinn approved these changes

2022-12-16 07:08 UTC, merged