EWPP-3108: Improve view modes for Person content type.
openeuropa/oe_theme pull request #1245
Opened 2023-02-16 11:32 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2023-02-20 09:30 UTC, 22Alexandra requested changes

2023-02-20 09:30 UTC, 22Alexandra commented on modules/oe_theme_content_person/templates/oe-theme-content-person-job-list.html.twig
> +  <div class="ecl-u-type-m ecl-u-type-bold ecl-u-mb-xs">{{ item.label }}</div>
This margin bottom (`ecl-u-mb-xs`) is causing a misalignment when there is no label.
<img width="610" alt="misalignment" src="https://user-images.githubusercontent.com/22908988/220060365-296035e5-fe39-4e8e-9af8-9fee3352bee0.png">

2023-02-20 09:30 UTC, 22Alexandra commented on modules/oe_theme_content_person/oe_theme_content_person.post_update.php
> +function oe_theme_content_person_post_update_30002() {
Missing return type.

2023-02-20 09:30 UTC, 22Alexandra commented on modules/oe_theme_content_person/oe_theme_content_person.post_update.php
> +  $storage = new FileStorage(drupal_get_path('module', 'oe_theme_content_person') . '/config/post_updates/30002_update_view_displays');
Let's replace the deprecated function `drupal_get_path`.

2023-02-20 09:30 UTC, 22Alexandra commented on modules/oe_theme_content_person/oe_theme_content_person.post_update.php
> +    // to be translated via the locale system as well.
Let's update this comment because we're not creating the config but updating it.

2023-02-20 09:30 UTC, 22Alexandra commented on modules/oe_theme_content_person/src/Plugin/ExtraField/Display/PersonJobLabelExtraField.php
> +      return [];
We should not return empty arrays. Please use the `$isEmpty` variable.

2023-02-20 09:30 UTC, 22Alexandra commented on modules/oe_theme_content_person/src/Plugin/ExtraField/Display/PersonJobListExtraField.php
> +      $build = [];
We need to use the same variable as above, i.e. `$isEmpty`.
Please remove the `$body` initialisation from line 107 because we don't need it.

2023-02-20 14:59 UTC, 22Alexandra approved these changes, later dismissed

2023-03-03 07:08 UTC, 22Alexandra approved these changes, later dismissed

2023-03-09 09:13 UTC, upchuk approved these changes

2023-03-09 09:13 UTC, 22Alexandra approved these changes

2023-03-09 09:13 UTC, merged