EWPP-3271: Theme Banner paragraph using the new ECL Banner component.
openeuropa/oe_theme pull request #1267
Opened 2023-04-25 15:07 UTC by 22Alexandra

2023-05-12 16:26 UTC, nagyad requested changes

2023-05-12 16:26 UTC, nagyad commented on templates/patterns/banners/banner_hero.ui_patterns.yml
> +  description: "Hero banner displays a prominent message and related action. It can have an image as background. The pattern will be deprecated in the next release. Use the Banner pattern instead."
After this PR merged it is deprecated already, so indicate when this will be removed instead.

2023-05-12 16:26 UTC, nagyad commented on templates/patterns/banners/banner_page.ui_patterns.yml
> +  description: "A page banner is smaller than a Hero banner. The pattern will be deprecated in the next release. Use the Banner pattern instead."
Same here.

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +    $en_file = \Drupal::service('file.repository')->writeData(file_get_contents(\Drupal::service('extension.list.theme')->getPath('oe_theme') . '/tests/fixtures/example_1.jpeg'), 'public://example_1_
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +    $bg_file = \Drupal::service('file.repository')->writeData(file_get_contents(\Drupal::service('extension.list.theme')->getPath('oe_theme') . '/tests/fixtures/example_1.jpeg'), 'public://example_1_
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +      'url(' . \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_uri),
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +      'url(' . \Drupal::service('file_url_generator')->generateAbsoluteString($bg_file_uri),
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +      'url(' . \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_uri),
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +      'url(' . \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_uri),
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +      'url(' . \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_uri),
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +      'url(' . \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_uri),
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +      'url(' . \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_uri),
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +      'url(' . \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_uri),
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +      'url(' . \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_uri),
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +      'url(' . \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_uri),
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +      'url(' . \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_uri),
$this->container->

2023-05-12 16:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +      'url(' . (\Drupal::service('file_url_generator')->generateAbsoluteString($av_portal_file_uri)),
$this->container->

2023-05-15 09:15 UTC, nagyad approved these changes

2023-05-15 09:16 UTC, nagyad submitted a review, later dismissed

2023-05-16 06:47 UTC, imanoleguskiza requested changes

2023-05-16 06:47 UTC, imanoleguskiza commented on oe_theme.theme
> +  $thumbnail = $media->get('thumbnail')->first();
Same as in the carousel, lets use the actual image, not the thumbnail

2023-05-16 06:47 UTC, imanoleguskiza commented on modules/oe_theme_paragraphs_banner/oe_theme_paragraphs_banner.info.yml
> +name: OpenEuropa Theme Paragraphs Banner
LEts enable the module in the runner file for clean installs

2023-05-16 09:33 UTC, imanoleguskiza submitted a review, later dismissed

2023-05-16 14:25 UTC, nagyad submitted a review, later dismissed

2023-05-16 14:27 UTC, nagyad approved these changes

2023-05-16 14:27 UTC, imanoleguskiza approved these changes

2023-05-16 14:28 UTC, merged