EWPP-3273: Update Carousel pattern and paragraph rendering.
openeuropa/oe_theme pull request #1269
Opened 2023-05-02 08:00 UTC by 22Alexandra

2023-05-10 10:26 UTC, nagyad requested changes

2023-05-10 10:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +    $en_file_1 = \Drupal::service('file.repository')->writeData(file_get_contents(\Drupal::service('extension.list.theme')->getPath('oe_theme') . '/tests/fixtures/example_1.jpeg'), 'public://example_
$this->container->

2023-05-10 10:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +    $bg_file_1 = \Drupal::service('file.repository')->writeData(file_get_contents(\Drupal::service('extension.list.theme')->getPath('oe_theme') . '/tests/fixtures/example_1.jpeg'), 'public://example_
$this->container->

2023-05-10 10:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +    $bg_file_2 = \Drupal::service('file.repository')->writeData(file_get_contents(\Drupal::service('extension.list.theme')->getPath('oe_theme') . '/tests/fixtures/example_1.jpeg'), 'public://example_
$this->container->

2023-05-10 10:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +          'image' => \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_1_uri),
$this->container->

2023-05-10 10:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +          'image' => \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_2_uri),
$this->container->

2023-05-10 10:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +          'image' => \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_1_uri),
$this->container->

2023-05-10 10:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +          'image' => \Drupal::service('file_url_generator')->generateAbsoluteString($en_file_2_uri),
$this->container->

2023-05-10 10:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +    $expected_values['items'][0]['image'] = \Drupal::service('file_url_generator')->generateAbsoluteString($bg_file_1_uri);
$this->container->

2023-05-10 10:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +    $expected_values['items'][1]['image'] = \Drupal::service('file_url_generator')->generateAbsoluteString($bg_file_2_uri);
$this->container->

2023-05-10 10:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +    $expected_values['items'][2]['image'] = \Drupal::service('file_url_generator')->generateAbsoluteString($bg_file_1_uri);
$this->container->

2023-05-10 10:26 UTC, nagyad commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +    $expected_values['items'][3]['image'] = \Drupal::service('file_url_generator')->generateAbsoluteString($bg_file_2_uri);
$this->container->

2023-05-11 12:03 UTC, nagyad approved these changes, later dismissed

2023-05-15 09:18 UTC, imanoleguskiza requested changes

2023-05-15 09:18 UTC, imanoleguskiza commented on oe_theme.theme
> +    $thumbnail = $media->get('thumbnail')->first();
Why are we using the thumbnail all of a sudden? We can just create the styled image by loading it and using the $uri we already generated no?
    $style = \Drupal::entityTypeManager()->getStorage('image_style')->load('oe_theme_full_width');
   $style->buildUrl($uri)

2023-05-16 07:57 UTC, imanoleguskiza submitted a review, later dismissed

2023-05-16 15:43 UTC, nagyad approved these changes

2023-05-22 06:51 UTC, imanoleguskiza approved these changes

2023-05-22 06:51 UTC, merged