EWPP-3296: Theme the Media paragraph.
openeuropa/oe_theme pull request #1270
Opened 2023-05-11 10:05 UTC by 22Alexandra

2023-05-15 13:06 UTC, nagyad requested changes

2023-05-15 13:06 UTC, nagyad commented on oe_theme.theme
> +  $cacheability = CacheableMetadata::createFromRenderArray($variables);
Why to create this here if you bail out after when the media entity is not available anymore in line 2226?

2023-05-15 13:06 UTC, nagyad commented on oe_theme.theme
> +  $cacheability->applyTo($variables);
You already apply the cache of the $variables in line 2275 and after that you don't add anything to it, so this is not needed.

2023-05-15 13:06 UTC, nagyad commented on oe_theme.theme
> +    $cacheability->applyTo($variables);
You already apply the cache of the $variables in line 2275 and after that you don't add anything to it, so this is not needed.

2023-05-15 13:47 UTC, 22Alexandra commented on oe_theme.theme
> +  $cacheability = CacheableMetadata::createFromRenderArray($variables);
It's created after making sure a media item exists. Why would it be created before?

2023-05-15 13:49 UTC, 22Alexandra commented on oe_theme.theme
> +    $cacheability->applyTo($variables);
Not really, that's for video media items. After we finish preprocessing the video, we return on 2282.

2023-05-15 13:52 UTC, 22Alexandra commented on oe_theme.theme
> +  $cacheability->applyTo($variables);
Same as below, on 2275 we apply the cache for the video item and then we return. 
Here we apply the cache that contains only the translated media and it's access which means we don't a video or an image anymore.

2023-05-15 16:15 UTC, nagyad submitted a review, later dismissed

2023-05-16 10:33 UTC, imanoleguskiza requested changes

2023-05-16 10:33 UTC, imanoleguskiza commented on oe_theme.theme
> +      $variables['ratio'] = '16:9';
This seems to be messing up with the height of avportal v ideos

2023-05-22 07:56 UTC, imanoleguskiza approved these changes, later dismissed

2023-05-22 09:58 UTC, nagyad approved these changes, later dismissed

2023-06-15 09:42 UTC, nagyad requested changes

2023-06-15 09:42 UTC, nagyad commented on composer.json
> +        "openeuropa/oe_paragraphs": "dev-EWPP-3295",
Needs merge first.

2023-06-15 09:45 UTC, nagyad approved these changes

2023-06-15 09:48 UTC, hernani approved these changes

2023-06-15 10:13 UTC, merged