EWPP-3310: Update ecl version, dependencies and node version.
openeuropa/oe_theme pull request #1271
Opened 2023-05-12 12:09 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2023-05-17 06:11 UTC, 22Alexandra approved these changes, later dismissed

2023-05-22 12:52 UTC, imanoleguskiza requested changes

2023-05-22 12:52 UTC, imanoleguskiza commented on templates/patterns/list_with_illustration/pattern-list-with-illustration.html.twig
> +      'img': null,
Do we need to set this variable?

2023-05-23 05:32 UTC, imanoleguskiza submitted a review, later dismissed

2023-05-23 05:37 UTC, 22Alexandra submitted a review, later dismissed

2023-06-08 11:29 UTC, 22Alexandra approved these changes

2023-06-08 11:30 UTC, nagyad approved these changes

2023-06-08 11:30 UTC, merged