EWPP-3315: Remove projecy budget fallback logic.
openeuropa/oe_theme pull request #1277
Opened 2023-06-01 15:17 UTC by nagyad

2023-06-06 11:16 UTC, 22Alexandra requested changes

2023-06-06 11:16 UTC, 22Alexandra commented on modules/oe_theme_content_project/src/Plugin/ExtraField/Display/OverallBudgetExtraField.php
> +    if ($entity->get('oe_project_eu_budget')->isEmpty()) {
We should not return empty arrays but use the isEmpty property.

2023-06-06 11:16 UTC, 22Alexandra commented on modules/oe_theme_content_project/src/Plugin/ExtraField/Display/PercentageExtraField.php
> +    $budget_eu = $entity->get('oe_project_eu_contrib')->value;
We're still rendering 0% contribution which I don't think is needed.

2023-06-07 06:42 UTC, 22Alexandra commented on modules/oe_theme_content_project/src/Plugin/ExtraField/Display/OverallBudgetExtraField.php
> +    if ($entity->get('oe_project_eu_budget')->isEmpty()) {
Ok this is good now but we still need to `return;` when there is nothing else to do.

2023-06-07 07:10 UTC, 22Alexandra requested changes

2023-06-07 07:10 UTC, 22Alexandra commented on modules/oe_theme_content_project/src/Plugin/ExtraField/Display/PercentageExtraField.php
> +      $this->isEmpty = TRUE;
Same as above.

2023-06-07 07:34 UTC, 22Alexandra commented on modules/oe_theme_content_project/src/Plugin/ExtraField/Display/OverallBudgetExtraField.php
> +    if ($entity->get('oe_project_eu_budget')->isEmpty()) {
Nvm.

2023-06-07 07:34 UTC, 22Alexandra submitted a review, later dismissed

2023-06-19 14:42 UTC, sergepavle requested changes

2023-06-19 14:42 UTC, sergepavle commented on modules/oe_theme_content_project/src/Plugin/ExtraField/Display/PercentageExtraField.php
> +    if (!$entity->get('oe_project_eu_contrib')->isEmpty() && !$entity->get('oe_project_eu_contrib')->isEmpty()) {
Repeated condition

2023-06-20 07:04 UTC, sergepavle approved these changes

2023-06-20 07:29 UTC, 22Alexandra approved these changes

2023-06-29 07:49 UTC, 22Alexandra approved these changes

2023-06-29 10:55 UTC, merged