EWPP-3347: Update ECL to 3.8.2 version.
openeuropa/oe_theme pull request #1282
Opened 2023-06-09 09:27 UTC by nagyad

2023-06-11 07:13 UTC, 22Alexandra submitted a review, later dismissed

2023-06-12 13:17 UTC, 22Alexandra submitted a review, later dismissed

2023-06-13 11:43 UTC, sergepavle submitted a review, later dismissed

2023-06-16 12:58 UTC, 22Alexandra requested changes
Please cleanup previous tags [0.3347.202306151647](https://github.com/openeuropa/oe_theme/releases/tag/0.3347.202306151647) and [0.3347.202306121741](https://github.com/openeuropa/oe_theme/releases/tag/0.3347.202306121741), create a new tag and update in ewcms.

2023-06-16 14:34 UTC, 22Alexandra submitted a review, later dismissed

2023-06-19 08:23 UTC, sergepavle submitted a review, later dismissed

2023-06-21 06:48 UTC, 22Alexandra approved these changes

2023-06-21 06:53 UTC, upchuk approved these changes

2023-06-21 06:55 UTC, merged