EWPP-3479: Add optional expandable block to Text with featured media pattern.
openeuropa/oe_theme pull request #1307
Opened 2023-08-01 15:27 UTC by 22Alexandra

2023-08-11 07:19 UTC, sergepavle approved these changes, later dismissed

2023-08-18 09:07 UTC, nagyad requested changes
There are errors on the event form and event page. Not sure if it is related. 
![image](https://github.com/openeuropa/oe_theme/assets/22004498/a74dc6a7-f40c-4ff1-9113-c349d1f34cbc)

2023-08-18 10:36 UTC, nagyad requested changes

2023-08-18 10:36 UTC, nagyad commented on tests/src/PatternAssertions/TextFeaturedMediaAssert.php
> +    self::assertStringContainsString('icons.svg#corner-arrow', $svg->attr('xlink:href'));
Why not $this-> ? You are not in a static context.

2023-08-18 10:36 UTC, nagyad commented on tests/src/PatternAssertions/TextFeaturedMediaAssert.php
> +    self::assertEquals($expected_block['content'], $content->text());
Why not $this-> ? You are not in a static context.

2023-08-18 12:07 UTC, 22Alexandra commented
> There are errors on the event form and event page. Not sure if it is related. ![image](https://user-images.githubusercontent.com/22004498/261558145-a74dc6a7-f40c-4ff1-9113-c349d1f34cbc.png)

They're not related and they are generated by the helptext added by the Media modules regarding the allowed media types:
```Type part of the media name. See the [media list](http://127.0.0.1:8080/build/en/admin/content/media) (opens a new window) to help locate media. Allowed media types: AV Portal Photo, AV Portal Video, Image, Remote video, ,``` 
Basically the Iframe and Video iframe media types are allowed in the field but the module creating them is not installed. I fixed the dependencies in oe_content.

2023-08-21 11:48 UTC, nagyad submitted a review, later dismissed

2023-08-24 17:38 UTC, sergepavle approved these changes, later dismissed

2023-09-01 13:03 UTC, sergepavle submitted a review, later dismissed

2023-09-12 08:04 UTC, nagyad approved these changes

2023-09-12 08:04 UTC, sergepavle approved these changes

2023-09-12 08:04 UTC, merged