EWPP-3647: Add Accessibility link to standardised footer blocks.
openeuropa/oe_theme pull request #1328
Opened 2023-10-11 07:01 UTC by 22Alexandra

2023-10-13 11:41 UTC, imanoleguskiza requested changes

2023-10-13 11:41 UTC, imanoleguskiza commented on oe_theme.theme
> +  $site_information = \Drupal::service('oe_corporate_site_info.site_information');
We need to check if the module is enabled before we get the service, the module is added as require_dev so not all sites will have it.

2023-10-16 07:03 UTC, imanoleguskiza submitted a review, later dismissed

2023-10-26 10:06 UTC, nagyad requested changes

2023-10-26 10:06 UTC, nagyad commented on oe_theme.theme
> +    return;
We create cacheability before and we add the configuration to the cache, however at this point we do not apply the cache to the render array. So either move the cache creation below this statement, or propagate the cache.

2023-10-26 10:06 UTC, nagyad commented on oe_theme.theme
> +    if ($entity_type_id === 'node' && $entity = \Drupal::entityTypeManager()->getStorage($entity_type_id)->load($entity_id)) {
Load the entity outside the argument and check if it's an instance of NodeInterface.

2023-10-26 13:18 UTC, nagyad approved these changes, later dismissed

2023-11-09 08:21 UTC, upchuk approved these changes

2023-11-09 08:22 UTC, hernani approved these changes

2023-11-09 08:22 UTC, merged