EWPP-3761: Update banner pattern and paragraph.
openeuropa/oe_theme pull request #1340
Opened 2023-12-02 10:01 UTC by 22Alexandra

2023-12-04 14:15 UTC, imanoleguskiza requested changes

2023-12-04 14:15 UTC, imanoleguskiza commented on templates/patterns/banners/pattern-banner-page.html.twig
>    {% include '@ecl-twig/page-banner' with {
We should replace this one as well right?

2023-12-05 15:58 UTC, nagyad submitted a review, later dismissed

2023-12-08 11:07 UTC, imanoleguskiza approved these changes

2023-12-08 11:53 UTC, nagyad approved these changes

2023-12-08 13:06 UTC, merged