EWPP-3763: Remove double icon from active search filters.
openeuropa/oe_theme pull request #1342
Opened 2023-12-04 09:49 UTC by imanoleguskiza

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2023-12-04 12:43 UTC, 22Alexandra requested changes
The test \Drupal\Tests\oe_theme\Kernel\RenderingTest::testRendering is currently skipped but the pattern's rendering assertions need to be updated in the `rendering.yml` file.

2023-12-04 12:57 UTC, 22Alexandra submitted a review, later dismissed

2023-12-04 13:47 UTC, nagyad submitted a review, later dismissed

2023-12-11 16:42 UTC, 22Alexandra submitted a review, later dismissed

2023-12-14 12:37 UTC, 22Alexandra submitted a review, later dismissed

2023-12-15 09:59 UTC, 22Alexandra approved these changes

2023-12-15 10:00 UTC, nagyad approved these changes

2023-12-15 10:09 UTC, merged