EWPP-3768: Add inverted styles for EC Footer links.
openeuropa/oe_theme pull request #1343
Opened 2023-12-04 10:01 UTC by imanoleguskiza

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2023-12-10 09:50 UTC, 22Alexandra requested changes
We need to set `inverted: true` for the Accessibility link in `oe-corporate-blocks-ec-footer--standardised.html.twig` to avoid this:
<img width="402" alt="ec standardised - accessibility link" src="https://github.com/openeuropa/oe_theme/assets/22908988/3dcaed3f-2d20-44c8-95f0-da844a5b0ab3">

2023-12-11 09:40 UTC, 22Alexandra submitted a review, later dismissed

2023-12-11 15:45 UTC, nagyad approved these changes

2023-12-11 15:45 UTC, 22Alexandra approved these changes

2023-12-11 16:37 UTC, merged