EWPP-3807: Fix ecl tables.
openeuropa/oe_theme pull request #1347
Opened 2023-12-05 13:48 UTC by imanoleguskiza

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2023-12-05 14:31 UTC, 22Alexandra requested changes

2023-12-05 14:31 UTC, 22Alexandra commented on templates/ui_patterns_library/patterns-meta-information.html.twig
> +      { data: [
We need to do this change in `patterns-variant-meta-information.html.twig` as well.

2023-12-05 14:34 UTC, 22Alexandra submitted a review, later dismissed

2023-12-05 15:40 UTC, nagyad submitted a review, later dismissed

2023-12-08 13:51 UTC, nagyad approved these changes

2023-12-11 10:36 UTC, 22Alexandra approved these changes

2023-12-11 10:37 UTC, nagyad approved these changes

2023-12-11 12:23 UTC, merged