EWPP-3912: Adapt site and page header templates.
openeuropa/oe_theme pull request #1379
Opened 2024-01-19 11:47 UTC by 22Alexandra

2024-01-24 14:21 UTC, nagyad requested changes

2024-01-24 14:21 UTC, nagyad commented on tests/src/Functional/SiteHeaderTest.php
> +      file_put_contents('test.html', $this->getSession()->getPage()->getOuterHtml());
Debug code to be removed.

2024-01-30 12:28 UTC, ademarco commented on templates/patterns/navigation_menu/navigation_menu.ui_patterns.yml
> +        hide_label: false
This changes the API of this particular pattern, could we, instead, hide the change in the pattern implementation, so that preview stays `Close` and then we add that array in the pattern itself. The button is just the close button anyway, we can only offer the possibility to change its label.

2024-01-30 12:28 UTC, ademarco commented on templates/patterns/navigation_menu/pattern-navigation-menu.html.twig
> +        size: close.icon_size,
See comment above, here just hard code values for the close button and leave only the label to be customizable.

2024-01-30 12:28 UTC, ademarco commented on tests/src/Functional/SiteHeaderTest.php
> +      file_put_contents('test.html', $this->getSession()->getPage()->getOuterHtml());
@22Alexandra yep, let's remove this if not needed.

2024-01-30 12:50 UTC, ademarco submitted a review, later dismissed

2024-01-31 08:55 UTC, ademarco approved these changes

2024-01-31 09:12 UTC, nagyad approved these changes

2024-01-31 09:12 UTC, merged