EWPP-3874: Update Event CT.
openeuropa/oe_theme pull request #1383
Opened 2024-01-24 17:01 UTC by 22Alexandra

2024-01-26 10:48 UTC, imanoleguskiza requested changes

2024-01-26 10:48 UTC, imanoleguskiza commented on modules/oe_theme_content_event/templates/oe-theme-content-event-contacts.html.twig
> +          <div{{ not loop.last ? ' class="ecl-u-mb-xl ecl-u-pb-xl ecl-u-border-bottom {{ ecl_class_border_color() }}"'}}>
We have two prints inside one another ({{ ecl_class_border_color() }} is inside another {{ }}) and it just prints it as a string. The resulting div is: <div class="ecl-u-mb-xl ecl-u-pb-xl ecl-u-border-bottom {{ ecl_class_border_color() }}">

2024-01-26 10:48 UTC, imanoleguskiza commented on modules/oe_theme_content_event/templates/oe-theme-content-event-contacts.html.twig
> +          <div{{ not loop.last ? ' class="ecl-u-mb-xl ecl-u-pb-xl ecl-u-border-bottom {{ ecl_class_border_color() }}"'}}>
I think this is not tested either in tests/src/Functional/ContentEventRenderTest.php so maybe a good time to add an assertion for it.

2024-01-29 08:33 UTC, imanoleguskiza submitted a review, later dismissed

2024-01-30 10:27 UTC, ademarco commented
@22Alexandra looks good but we have an issue with the calendar icon on mobile devices, see GIF below:

![Peek 2024-01-30 11-26](https://github.com/openeuropa/oe_theme/assets/153362/a962461e-e895-4a9c-b4ac-d1cd627eb697)

2024-01-30 11:55 UTC, 22Alexandra commented
> @22Alexandra looks good but we have an issue with the calendar icon on mobile devices, see GIF below:
> 
> ![Peek 2024-01-30 11-26](https://private-user-images.githubusercontent.com/153362/300771981-a962461e-e895-4a9c-b4ac-d1cd627eb697.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTA5MTUsIm5iZiI6MTcwNjYxMDYxNSwicGF0aCI6Ii8xNTMzNjIvMzAwNzcxOTgxLWE5NjI0NjFlLWU4OTUtNGE5Yy1iNGFjLWQxY2Q2MjdlYjY5Ny5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMDMwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmU2YWJkMzdhNmQxNDg1NDFmOTIyYzA5ZjViZGJjNWE4ODMwYmY3ZmMyNWRlOTNiYWIyNDIyZTE5NDU2YmZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zONXhfEHU1m0hSpt0pyE5GhiaSk_CJ07E14M_89NeRM)

Unfortunately, there is not much to be fixed regarding this. This happens for any inline icon with long text in comparison with the inline icons with shorter text because it will need to fit the text on two lines. Please take a look the following video:

https://github.com/openeuropa/oe_theme/assets/22908988/4e66a56b-52d7-4cea-8d7b-6ad98e7eafb1

2024-01-30 12:20 UTC, ademarco approved these changes, later dismissed

2024-01-30 12:21 UTC, ademarco commented
I see, it's an upstream problem, we should open a ticket on ECL then, I'll approve this for the time being.

2024-01-31 11:03 UTC, upchuk approved these changes

2024-01-31 11:10 UTC, sergepavle approved these changes

2024-01-31 11:10 UTC, merged