EWPP-3877: Reactivate page content type tests.
openeuropa/oe_theme pull request #1386
Opened 2024-01-29 10:16 UTC by nagyad

2024-01-29 14:16 UTC, 22Alexandra requested changes

2024-01-29 14:16 UTC, 22Alexandra commented on tests/src/Kernel/LegacyContentRenderTest.php
> +    $related_links = $crawler->filter('div.ecl-u-border-bottom.ecl-u-border-color-neutral-40.ecl-u-pt-m.ecl-u-pb-m a');
This needs to be changed in the field template as well.
Also, on line 66 the selector for the ECL Content item component doesn't use an h1 tag for the title anymore, I believe it's a div so it should be fixed too.

2024-01-29 16:06 UTC, 22Alexandra approved these changes

2024-02-01 08:36 UTC, 22Alexandra approved these changes

2024-02-01 08:40 UTC, sergepavle approved these changes
for @imanoleguskiza

2024-02-01 09:29 UTC, merged