EWPP-3873: Update tests for "Consultation" content type.
openeuropa/oe_theme pull request #1390
Opened 2024-01-29 23:02 UTC by fmmribeiro

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-01-31 07:21 UTC, 22Alexandra requested changes

2024-01-31 07:21 UTC, 22Alexandra commented on tests/src/Functional/ContentConsultationRenderTest.php
> +
This extra space can be removed.

2024-01-31 07:21 UTC, 22Alexandra commented on tests/src/Functional/ContentRenderTestBase.php
> +use Drupal\Tests\oe_theme\PatternAssertions\SocialMediaLinksAssert;
Doesn't seem to be used, should be removed.

2024-01-31 07:21 UTC, 22Alexandra commented on tests/src/Kernel/ConsultationRenderTest.php
> +
This extra space can be removed.

2024-01-31 07:24 UTC, 22Alexandra commented on tests/src/Functional/ContentRenderTestBase.php
> +use Drupal\Tests\oe_theme\PatternAssertions\SocialMediaLinksAssert;
Nvm, it's used in here `assertContactDetailsRender()`.

2024-01-31 08:24 UTC, 22Alexandra approved these changes

2024-01-31 09:51 UTC, nagyad approved these changes, later dismissed

2024-01-31 15:30 UTC, sergepavle approved these changes

2024-01-31 15:46 UTC, 22Alexandra approved these changes, later dismissed

2024-01-31 15:47 UTC, sergepavle approved these changes, later dismissed

2024-02-01 06:13 UTC, 22Alexandra approved these changes

2024-02-01 07:46 UTC, sergepavle approved these changes

2024-02-01 07:47 UTC, merged