EWPP-3880: Fix content type "Project" tests.
openeuropa/oe_theme pull request #1394
Opened 2024-01-30 20:28 UTC by fmmribeiro

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-02-02 07:48 UTC, 22Alexandra requested changes
We need to fix our custom css because they don't seem to look right:
<img width="605" alt="EU" src="https://github.com/openeuropa/oe_theme/assets/22908988/c9248984-08e0-4de1-b78d-56cae9537319">
<img width="623" alt="EC" src="https://github.com/openeuropa/oe_theme/assets/22908988/9130997e-c233-40bd-a847-b54ecaeb6408">

I didn't find the featured variant of the description list component in ECL v4, perhaps they removed it. However, we have our own custom css where we applyborder and background color (check `_description_list.scss`). We need to fix the colors on both EC and EU components because for now they look the same since the colors we apply in that file do not exist anymore.
Check the `eclBorderColor` and `eclBackgroundColor` twig functions where we define colors based on the component library so the same ones should be used for this case.

2024-02-05 08:59 UTC, 22Alexandra requested changes

2024-02-05 08:59 UTC, 22Alexandra commented on sass/style-ec.scss
> +
No need to override the variable values since you're setting the default ones.
```suggestion
@use "./components/description_list";
```

2024-02-05 11:22 UTC, 22Alexandra approved these changes

2024-02-06 14:55 UTC, nagyad approved these changes

2024-02-06 15:58 UTC, merged