EWPP-3987: Restore build to use an actual ECL4 release
openeuropa/oe_theme pull request #1398
Opened 2024-02-09 10:14 UTC by ademarco

2024-02-16 08:27 UTC, 22Alexandra commented on patches/@ecl/twig-component-site-footer+3.13.0.patch
> -+      - "aria_label" (string) aria-label attribute for the logo link
We need this patch back in order to use the aria_label and title parameters that we're passing in our oe-corporate-blocks footer templates.

2024-02-16 08:32 UTC, 22Alexandra commented on patches/@ecl+twig-component-file+4.0.0-beta-1.patch
> ++        {{- _description -}}
This doesn't seem to get displayed. I think something is wrong in the patch.

2024-02-16 08:34 UTC, 22Alexandra requested changes
We will need these 2 libraries https://github.com/openeuropa/oe_theme/pull/1398/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L46-L47 required in the package.json.

2024-02-19 06:16 UTC, 22Alexandra approved these changes

2024-02-19 12:38 UTC, imanoleguskiza approved these changes

2024-02-19 12:39 UTC, merged