EWPP-3957: Fix content moderation form appearance.
openeuropa/oe_theme pull request #1401
Opened 2024-02-13 22:53 UTC by fmmribeiro

2024-02-15 08:23 UTC, 22Alexandra approved these changes

2024-02-15 08:24 UTC, 22Alexandra requested changes
The PR looks fine but it's needs to be rebased on the 4.x branch.

2024-02-15 11:57 UTC, 22Alexandra approved these changes

2024-02-19 11:38 UTC, sergepavle approved these changes

2024-02-20 09:47 UTC, 22Alexandra approved these changes

2024-02-20 10:01 UTC, sergepavle approved these changes

2024-02-20 10:39 UTC, merged