EWPP-4045: Replace blue ecl color class and fix font-family.
openeuropa/oe_theme pull request #1403
Opened 2024-02-14 16:01 UTC by 22Alexandra

2024-02-19 13:22 UTC, nagyad submitted a review, later dismissed

2024-02-20 08:21 UTC, imanoleguskiza requested changes
We

2024-02-20 08:21 UTC, imanoleguskiza commented on sass/components/_global.scss
> +  font-family: $font-family;
We should do the same in _contextual_navigation.scss

2024-02-20 09:01 UTC, imanoleguskiza approved these changes

2024-02-20 12:01 UTC, nagyad approved these changes

2024-02-20 12:32 UTC, nagyad approved these changes

2024-02-20 13:58 UTC, imanoleguskiza approved these changes

2024-02-20 15:48 UTC, merged