EWPP-3982: Use monochrome social network icons.
openeuropa/oe_theme pull request #1408
Opened 2024-02-16 17:38 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-02-20 13:08 UTC, 22Alexandra requested changes
We seem to be using the wrong social media icons in Contact entities:
<img width="729" alt="social icon in contact entity" src="https://github.com/openeuropa/oe_theme/assets/22908988/1ea3025c-2504-4969-9e9b-3387cc268ad8">

We should be using the social media icons from the `icons-social-media` directory. Could we fix that?

2024-02-22 06:14 UTC, 22Alexandra approved these changes

2024-02-22 14:27 UTC, nagyad approved these changes

2024-02-26 11:33 UTC, 22Alexandra approved these changes

2024-02-26 13:08 UTC, merged