EWPP-4137: Cleanup deprecated patterns and fields and update README.
openeuropa/oe_theme pull request #1420
Opened 2024-02-27 10:33 UTC by 22Alexandra

2024-03-06 08:36 UTC, ademarco requested changes

2024-03-06 08:36 UTC, ademarco commented on modules/oe_theme_helper/src/TwigExtension/TwigExtension.php
> -
If we got NULL, in 3.x we were changing it to 0, what should we do now? We set the type to `int` in the argument?

```php
  public function smartTrim(Environment $env, $input, int $limit = 0) {
```

2024-03-06 09:35 UTC, ademarco approved these changes

2024-03-07 09:59 UTC, nagyad approved these changes

2024-03-08 08:25 UTC, merged