EWPP-4139: Add a variant field to navigation_list pattern.
openeuropa/oe_theme pull request #1438
Opened 2024-04-04 08:13 UTC by 22Alexandra

2024-04-08 08:33 UTC, imanoleguskiza requested changes

2024-04-08 08:33 UTC, imanoleguskiza commented on templates/patterns/navigation_list/navigation_list.ui_patterns.yml
> +    item_variant:
We should be using the patterns variant functionality like we have in banner

2024-04-09 14:56 UTC, imanoleguskiza approved these changes

2024-04-09 14:59 UTC, fmmribeiro approved these changes

2024-04-11 09:00 UTC, merged