EWPP-4356: Use source key of picture parameter for rendering different image sizes for each ECL breakpoint in Banner and Carousel.
openeuropa/oe_theme pull request #1456
Opened 2024-05-27 15:56 UTC by 22Alexandra

2024-06-05 09:20 UTC, fmmribeiro commented
Can the readme file be updated?
https://github.com/openeuropa/oe_theme?tab=readme-ov-file#image-styles

2024-06-05 11:44 UTC, nagyad requested changes

2024-06-05 11:44 UTC, nagyad commented on modules/oe_theme_helper/oe_theme_helper.post_update.php
> +    $style = \Drupal::entityTypeManager()->getStorage('image_style')->load($style_id);
Let's instantiate a `$storage = \Drupal::entityTypeManager()->getStorage('image_style');` outside of the foreach.

2024-06-05 11:44 UTC, nagyad commented on oe_theme.theme
> +  $small = \Drupal::entityTypeManager()->getStorage('image_style')->load('oe_theme_small_banner');
`$storage = \Drupal::entityTypeManager()->getStorage('image_style');`

2024-06-05 11:44 UTC, nagyad commented on oe_theme.theme
> +  $small = \Drupal::entityTypeManager()->getStorage('image_style')->load('oe_theme_small_banner');
`$storage = \Drupal::entityTypeManager()->getStorage('image_style')`

2024-06-05 11:44 UTC, nagyad commented on tests/src/PatternAssertions/CarouselAssert.php
> +        (isset($expected_item['variant']) && $expected_item['variant'] === 'plain-background')) {
This can go in one line.

2024-06-11 12:18 UTC, fmmribeiro approved these changes, later dismissed

2024-06-12 09:08 UTC, nagyad approved these changes, later dismissed

2024-07-15 14:00 UTC, nagyad submitted a review, later dismissed

2024-08-09 09:08 UTC, fmmribeiro approved these changes

2024-08-09 09:13 UTC, nagyad approved these changes

2024-08-09 09:14 UTC, merged