EWPP-4370: Add new field formatter and update entity view configs for…
openeuropa/oe_theme pull request #1458
Opened 2024-05-31 12:54 UTC by sergepavle

… Contact entity type.

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-06-04 09:33 UTC, 22Alexandra requested changes
Organisation CT still uses the old address format for the teaser display:
<img width="384" alt="Organisation teaser" src="https://github.com/openeuropa/oe_theme/assets/22908988/a9bfc116-f70e-43fc-a371-ea28fe225548">

The full display seems fine.

2024-06-04 09:33 UTC, 22Alexandra commented on modules/oe_theme_helper/src/Plugin/Field/FieldFormatter/AddressCommissionFormatter.php
> +  public static function updateFormat(&$string) {
Shouldn't this be protected?

2024-06-04 10:03 UTC, 22Alexandra commented on modules/oe_theme_helper/src/Plugin/Field/FieldFormatter/AddressCommissionFormatter.php
> +
```suggestion
```

2024-06-06 06:21 UTC, 22Alexandra approved these changes

2024-06-07 15:49 UTC, fmmribeiro approved these changes

2024-06-10 05:50 UTC, merged