EWPP-4383: Update gallery to render media name as title parameter.
openeuropa/oe_theme pull request #1460
Opened 2024-06-03 09:33 UTC by 22Alexandra

2024-06-04 11:40 UTC, sergepavle approved these changes, later dismissed

2024-06-05 06:43 UTC, upchuk requested changes

2024-06-05 06:43 UTC, upchuk commented on src/ValueObject/GalleryItemValueObject.php
> +    $this->title = $title;
Let's put the title as the last parameter to maintain some BC and values don't get set wrongly if someone uses this without a title.

2024-06-05 07:11 UTC, upchuk submitted a review, later dismissed

2024-06-07 10:43 UTC, merged