EWPP-4401: Pass hide_label variable to the social media links pattern.
openeuropa/oe_theme pull request #1469
Opened 2024-06-19 09:34 UTC by intelektron

## EWPP-4401

### Description

EWPP CMS defines a field that allows to hide social media labels, leaving only icons. However, the `hide_label` parameter is not passed to the pattern.

2024-06-19 13:26 UTC, 22Alexandra requested changes

2024-06-19 13:26 UTC, 22Alexandra commented on templates/patterns/social_media_links/pattern-social-media-links.html.twig
> +      hide_label: link.hide_label|default(false),
Let's update one of the links in `social_media_links.ui_patterns.yml` so it's also visible in the patterns overview page.

2024-06-20 10:27 UTC, 22Alexandra approved these changes

2024-07-18 08:04 UTC, 22Alexandra approved these changes

2024-07-19 11:13 UTC, nagyad approved these changes

2024-08-01 08:27 UTC, merged