EWPP-4509: Add new fields for Gallery pattern.
openeuropa/oe_theme pull request #1479
Opened 2024-07-15 10:41 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-07-15 13:18 UTC, 22Alexandra requested changes
Let's fix the ticket number in the commit message and PR title.

2024-07-15 13:18 UTC, 22Alexandra commented on templates/patterns/gallery/pattern-gallery.html.twig
> +  {% set ratio = ratio|default('3-2') %}
If the same name is used for the variables in the template, we rely on the ECL implementation so checking if the `grid` is enabled wouldn't be needed. Instead let's use different variable names to be passed to the ECL component.
```suggestion
  {% set _columns = columns|default(2) %}
  {% set _ratio = ratio|default('3-2') %}
```

2024-07-15 13:18 UTC, 22Alexandra commented on templates/patterns/gallery/pattern-gallery.html.twig
> +  'ratio': ratio|default(null),
Considering the comment above, let's rename the passed variables for columns and ratio.
```suggestion
  'column': _columns|default(null),
  'ratio': _ratio|default(null),
```

2024-07-15 13:18 UTC, 22Alexandra commented on templates/patterns/gallery/gallery.ui_patterns.yml
> +      label: "Column number"
It's not the column number.
```suggestion
      label: "Aspect ratio"
```

2024-07-15 13:18 UTC, 22Alexandra commented on templates/patterns/gallery/gallery.ui_patterns.yml
> +      preview: 2
This value for the preview is wrong and it's not working.

2024-07-15 13:18 UTC, 22Alexandra commented on templates/patterns/gallery/gallery.ui_patterns.yml
> +      escape: false
Do we need to escape a string?
Let's also add the empty new line at the end of the file.

2024-07-15 13:18 UTC, 22Alexandra commented on tests/src/Kernel/fixtures/rendering.yml
> +      '.ecl-gallery--ratio-3-1': 0
Values for `columns` and `ratio` should be provided in order to assert they are not used if grid is not enabled.

2024-07-16 05:39 UTC, 22Alexandra submitted a review, later dismissed

2024-07-16 12:43 UTC, nagyad approved these changes, later dismissed

2024-08-11 09:04 UTC, merged