EWPP-4551: Update ECL version.
openeuropa/oe_theme pull request #1481
Opened 2024-07-19 17:59 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-07-25 08:38 UTC, 22Alexandra requested changes
ECL 4.4.0 kinda removes the Banner component variants but keeps adding the classes to keep some sort of BC. Doing this, the rendering of the plain background variant is wrong: it renders both a plain background + the image if available.
<img width="1674" alt="plain background" src="https://github.com/user-attachments/assets/d0c2dfb9-b715-4f1b-9e7e-9d3b5ab44fe0">

This should not happen in EWCMS since the Plain background variant doesn't have an image field but we need to fix it in oe_theme. So, let's remove the image if available when rendering this variant. Please also add a test case to ensure this.

2024-07-26 05:28 UTC, 22Alexandra submitted a review, later dismissed

2024-07-26 10:33 UTC, nagyad submitted a review, later dismissed

2024-08-02 06:34 UTC, 22Alexandra approved these changes

2024-08-02 06:36 UTC, upchuk approved these changes

2024-08-02 06:51 UTC, nagyad approved these changes

2024-08-02 07:32 UTC, merged