ISSUE-293: Add template for Content row paragraph type Columns layout variant.
openeuropa/oe_theme pull request #295
Opened 2019-08-12 13:13 UTC by kp77

## ISSUE-293

### Description

openeuropa/oe_paragraphs#65 introduces a new variant (Columns Layout) for the 'content row' paragraph type. This issue is created to contribute the theming logic that will be responsible to render multi-column layouts for this new variant.

### Change log

- Added:
Template file for the new variant.
- Changed:
oe_theme.theme (added preprocess function for the new variant)
composer.json (added patch for oe_paragraphs new variant temporarily)

2019-08-12 14:07 UTC, msnassar submitted a review, later dismissed

2019-08-12 14:10 UTC, ademarco approved these changes

2019-08-12 14:14 UTC, ademarco requested changes
The two approvals above were just a test to test GitHub permissions. I'll block this PR until is ready for an actual review.

2019-12-20 11:35 UTC, sergepavle commented on oe_theme.theme
> +      $layout = array_fill(0, $column_count, $grid_column_count / $column_count);
By validation before we should avoid chance to get float number

2019-12-20 11:38 UTC, sergepavle commented on oe_theme.theme
> +      $layout = explode('-', $layout_settings) ?? [$grid_column_count];
Require validation that we have number of columns in sum equels 12.

2025-05-28 10:07 UTC, closed without merging