OPENEUROPA-2340: Implement site specific footer 1.x.
openeuropa/oe_theme pull request #340
Opened 2019-10-22 08:53 UTC by sergepavle

## OPENEUROPA-2340

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2019-10-28 13:29 UTC, imanoleguskiza requested changes

2019-10-28 14:28 UTC, imanoleguskiza approved these changes

2019-10-30 21:23 UTC, dxvargas approved these changes

2019-11-26 16:02 UTC, ademarco commented
We only support this on 2.x. Closing. #342

2019-11-26 16:02 UTC, closed without merging