OPENEUROPA-2474: Make sure that teaser display modes are properly themed.
openeuropa/oe_theme pull request #362
Opened 2019-11-11 14:19 UTC by sergepavle

## OPENEUROPA-2474

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2019-11-12 16:22 UTC, imanoleguskiza submitted a review, later dismissed

2019-11-13 14:16 UTC, nagyad commented on modules/oe_theme_content_news/oe_theme_content_news.post_update.php
> +    if ($effect->getPluginId() == 'image_scale_and_crop') {
===

2019-11-13 16:52 UTC, ademarco requested changes
This is flagged waiting for input from the PO.

2019-11-19 10:04 UTC, sergepavle commented on modules/oe_theme_content_news/oe_theme_content_news.post_update.php
> +    if ($effect->getPluginId() == 'image_scale_and_crop') {
Fixed

2019-11-19 10:06 UTC, sergepavle commented
> This is flagged waiting for input from the PO.

Already discussed with @kugta and we are agreed that this is not blocker.

2019-11-19 10:22 UTC, ademarco commented
Instead of changing the preset size we could use the largest one for now and then restore the original functionality once the ECL will provide it. Let's just add a comment to explain the reasoning behind using the larged preset we have.

2019-11-19 13:20 UTC, nagyad submitted a review, later dismissed

2019-11-20 12:47 UTC, ademarco approved these changes

2019-11-20 12:48 UTC, ademarco commented
As discussed with PO we will now use the largest image stile we have and restore the responsive behavior once ECL will allow us to do it again.

2019-11-20 12:50 UTC, imanoleguskiza approved these changes

2019-11-20 12:51 UTC, merged