OPENEUROPA-2479: Use a navigation menu pattern.
openeuropa/oe_theme pull request #371
Opened 2019-11-14 12:34 UTC by imanoleguskiza

## OPENEUROPA-2479

### Description

Add new navigation menu pattern.

### Change log

- Added: Navigation menu pattern.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2019-11-14 14:50 UTC, ademarco requested changes

2019-11-14 14:50 UTC, ademarco commented on oe_theme.theme
> +          $index = 0;
All this should be done in the twig template itself, remember the discussion we had about pattern preprocess being ran too early to process data such as this one?

2019-11-16 09:57 UTC, ademarco commented
The proposed solution doesn't not scale well:

![image](https://user-images.githubusercontent.com/153362/68991457-63f2e700-085f-11ea-8417-843cb9e00a0c.png)

In vertical variant we need to limit the number of columns, rather than the number of items that we can fit in each column, while in horizontal variant we this works well because we are limiting the number of items per row:

![image](https://user-images.githubusercontent.com/153362/68991477-9bfa2a00-085f-11ea-98fd-536177e835f9.png)

Also, let's make alignment a variant, I've tried if locally and it works well:

```diff
diff --git a/modules/oe_theme_helper/src/TwigExtension/Filters.php b/modules/oe_theme_helper/src/TwigExtension/Filters.php
index 745194b..0967947 100644
--- a/modules/oe_theme_helper/src/TwigExtension/Filters.php
+++ b/modules/oe_theme_helper/src/TwigExtension/Filters.php
@@ -233,7 +233,7 @@ class Filters extends \Twig_Extension {
    * @return array
    *   An array of properly grouped links.
    */
-  public function toEclMenuLinks(array $links, int $number = 4, string $alignment = 'horizontal'): array {
+  public function toEclMenuLinks(array $links, int $number = 1, string $alignment = 'horizontal'): array {
     foreach ($links as &$link) {
       if (!isset($link['children'])) {
         continue;
diff --git a/templates/navigation/menu--main.html.twig b/templates/navigation/menu--main.html.twig
index dc8e81f..6dc3eb3 100644
--- a/templates/navigation/menu--main.html.twig
+++ b/templates/navigation/menu--main.html.twig
@@ -6,7 +6,6 @@
  * @see ./core/themes/stable/templates/navigation/menu.html.twig
  */
 #}
-{{ attach_library('oe_theme/navigation') }}
 {% if links %}
   {{ pattern('navigation_menu', {
     label: 'Menu'|t,
diff --git a/templates/patterns/navigation_menu/navigation_menu.ui_patterns.yml b/templates/patterns/navigation_menu/navigation_menu.ui_patterns.yml
index 938b62a..e416030 100644
--- a/templates/patterns/navigation_menu/navigation_menu.ui_patterns.yml
+++ b/templates/patterns/navigation_menu/navigation_menu.ui_patterns.yml
@@ -1,6 +1,13 @@
 navigation_menu:
   label: "Navigation menu"
   description: "Default implementation of the main navigation menu."
+  variants:
+    vertical:
+      label: "Vertical"
+      description: "Menu items will be arranged vertically, the 'number' parameter indicates how many links each column will display (4 in the example below)."
+    horizontal:
+      label: "Horizontal"
+      description: "Menu items will be arranged vertically, the 'number' parameter indicates how many links each row will display (4 in the example below)."
   fields:
     label:
       type: "text"
@@ -51,11 +58,6 @@ navigation_menu:
     number:
       type: "numeric"
       label: "Number"
-      description: "The amount of link items to show in a submenu row or column"
+      description: "The amount of link items to show in a submenu row or column, check variant descriptions for more information."
       preview: 4
       escape: false
-    alignment:
-      type: "text"
-      label: "Alignment"
-      description: "Whether the menu items will be ordered horizontally or vertically. Defaults to horizontal."
-      preview: "horizontal"
diff --git a/templates/patterns/navigation_menu/pattern-navigation-menu.html.twig b/templates/patterns/navigation_menu/pattern-navigation-menu.html.twig
index 27c89ab..fc556b4 100644
--- a/templates/patterns/navigation_menu/pattern-navigation-menu.html.twig
+++ b/templates/patterns/navigation_menu/pattern-navigation-menu.html.twig
@@ -4,16 +4,11 @@
  * Default implementation for the navigation menu component.
  */
 #}
-
-
-{% set _number = number|default(1) %}
-{% set _alignment = alignment|default('horizontal') %}
-{% set _items = items|to_ecl_menu_links(_number, _alignment) %}
-
-{% if _items %}
+{% if items %}
+  {% set items = items|to_ecl_menu_links(number, variant) %}
   {% include '@ecl-twig/menu-legacy' with {
     label: label|default('Menu'),
-    items: _items,
+    items: items,
     icon_path: ecl_icon_path
   } only %}
 {% endif %}
diff --git a/tests/Kernel/fixtures/rendering.yml b/tests/Kernel/fixtures/rendering.yml
index cd4da30..1bc4de9 100644
--- a/tests/Kernel/fixtures/rendering.yml
+++ b/tests/Kernel/fixtures/rendering.yml
@@ -1545,7 +1545,6 @@
       'ul li.ecl-unordered-list__item:nth-child(1)': '<svg class="ecl-icon ecl-icon--m ecl-u-mr-s" focusable="false" aria-hidden="true"><use xlink:href="http://localhost/themes/custom/oe_theme/dist/ec/images/icons/sprites/icons.svg#general--file"></use></svg>Culture | Innovation'
       'ul li.ecl-unordered-list__item:nth-child(2)': '<svg class="ecl-icon ecl-icon--m ecl-u-mr-s" focusable="false" aria-hidden="true"><use xlink:href="http://localhost/themes/custom/oe_theme/dist/ec/images/icons/sprites/icons.svg#general--file"></use></svg>15-16 November 2019, 08:00 AM'
       'ul li.ecl-unordered-list__item:nth-child(3)': '<svg class="ecl-icon ecl-icon--m ecl-u-mr-s" focusable="false" aria-hidden="true"><use xlink:href="http://localhost/themes/custom/oe_theme/dist/ec/images/icons/sprites/icons.svg#general--livestreaming"></use></svg>Live streaming available'
-
 - array:
     '#type': "pattern"
     '#id': "tag"
@@ -1562,6 +1561,7 @@
 - array:
     '#type': "pattern"
     '#id': "navigation_menu"
+    '#variant': "horizontal"
     '#fields':
       label: "Menu"
       items:
@@ -1588,7 +1588,6 @@
         - href: "#"
           label: "Contact"
       number: 2
-      alignment: "horizontal"
   assertions:
     contains:
       '.ecl-menu-legacy__hamburger': "Menu"
@@ -1607,6 +1606,7 @@
 - array:
     '#type': "pattern"
     '#id': "navigation_menu"
+    '#variant': "vertical"
     '#fields':
       label: "Menu"
       items:
@@ -1633,7 +1633,6 @@
         - href: "#"
           label: "Contact"
       number: 2
-      alignment: "vertical"
   assertions:
     contains:
       '.ecl-menu-legacy__hamburger': "Menu"
```

2019-11-16 16:26 UTC, ademarco commented on templates/patterns/navigation_menu/pattern-navigation-menu.html.twig
> +    label: label|default('Menu'),
`t` function missing, it should be:
```
     label: label|default('Menu'|t),
```

2019-11-18 16:23 UTC, sergepavle approved these changes

2019-11-18 18:27 UTC, ademarco approved these changes

2019-11-18 18:27 UTC, merged