OPENEUROPA-2482: Add 4 / 6 columns layout and a link pattern
openeuropa/oe_theme pull request #373
Opened 2019-11-18 16:05 UTC by ademarco

2019-11-18 16:35 UTC, imanoleguskiza requested changes
The PR does what is set out to do and all the tests are correct. However were some decissions taken with regards of the styling of the content items and content item blocks that were not documented or approved. If we are happy to continue without explicit approval I'll approve the PR, otherwise we should contact the PrOw

2019-11-18 18:26 UTC, ademarco commented
Yep, true, I've actually actually done them with the PO on my side, getting near real time approval :+1:

2019-11-18 19:15 UTC, imanoleguskiza submitted a review, later dismissed

2019-11-19 10:07 UTC, imanoleguskiza approved these changes

2019-11-19 10:32 UTC, upchuk approved these changes

2019-11-19 10:32 UTC, merged