OPENEUROPA-2391: Switch between the EC and EU footer blocks.
openeuropa/oe_theme pull request #379
Opened 2019-11-22 16:40 UTC by ademarco

2019-11-25 14:04 UTC, nagyad requested changes

2019-11-25 14:04 UTC, nagyad commented on modules/oe_theme_helper/src/Plugin/Condition/CurrentComponentLibraryCondition.php
> +      return $this->t('The current component library is set to any value.');
I think it is better if we say "The current component library is not set."

2019-11-25 14:04 UTC, nagyad commented on modules/oe_theme_helper/src/Plugin/Condition/CurrentComponentLibraryCondition.php
> +    return parent::buildConfigurationForm($form, $form_state);
Empty line before return statement.

2019-11-25 14:04 UTC, nagyad commented on tests/Behat/OeThemeTestContext.php
> +   * Assert presence of absence of footer blocks.
Assert presence or absence of footer blocks.

2019-11-25 14:04 UTC, nagyad commented on tests/features/corporate-blocks.feature
> +  Scenario Outline: The European Commission footer or the European Union one si shown depending on the which style is chosen.
Typo in sentence.

2019-11-25 14:08 UTC, nagyad commented
Tested manually both upgrade path and the functionality.

2019-11-25 15:31 UTC, sergepavle requested changes

2019-11-25 15:31 UTC, sergepavle commented on oe_theme.info.yml
>      - block.block.oe_theme_corporate_footer
Should be removed/replaced to     `- block.block.oe_theme_eu_corporate_footer`.

2019-11-25 16:05 UTC, imanoleguskiza requested changes

2019-11-25 16:05 UTC, imanoleguskiza commented on modules/oe_theme_helper/src/Plugin/Condition/CurrentComponentLibraryCondition.php
> + * This condition check if the current component library is equal to a given
"This condition checks"

2019-11-25 16:05 UTC, imanoleguskiza commented on tests/Behat/OeThemeTestContext.php
> +   * @Then I should see :component_library footer( instead)
MIssing the article "I should see the :component_library"

2019-11-25 16:05 UTC, imanoleguskiza commented on tests/Behat/OeThemeTestContext.php
> +   * @Then I should not see :component_library footer( instead)
MIssing the article "I should see the :component_library"

2019-11-25 16:05 UTC, imanoleguskiza commented on tests/Behat/OeThemeTestContext.php
> +    $component_library_name = [
Should we define this as a constant or a class variable and reuse it in all the methods?

2019-11-25 16:12 UTC, ademarco commented on tests/Behat/OeThemeTestContext.php
> +    $component_library_name = [
I wouldn't, it's specific to converting human readable configuration into its machine value.

2019-11-25 16:17 UTC, ademarco commented on modules/oe_theme_helper/src/Plugin/Condition/CurrentComponentLibraryCondition.php
> +      return $this->t('The current component library is set to any value.');
That means that the condition is satisfied for any value of the component library.

2019-11-25 16:19 UTC, ademarco commented on modules/oe_theme_helper/src/Plugin/Condition/CurrentComponentLibraryCondition.php
> +      return $this->t('The current component library is set to any value.');
I've changed that to a more clear:
> The current component library can be set to anything

2019-11-25 16:26 UTC, sergepavle submitted a review, later dismissed

2019-11-25 16:41 UTC, sergepavle approved these changes

2019-11-25 17:04 UTC, imanoleguskiza approved these changes

2019-11-26 07:43 UTC, nagyad approved these changes

2019-11-26 07:43 UTC, merged