OPENEUROPA-2612: Remove underline from cards title.
openeuropa/oe_theme pull request #388
Opened 2019-12-04 10:55 UTC by 22Alexandra

## OPENEUROPA-2612

### Description

Remove underline from cards title.

### Change log

- Added:
- Changed: Set title variant and type to standalone for featured item pattern.
- Deprecated:
- Removed:
- Fixed:
- Security:

2019-12-04 14:39 UTC, nagyad submitted a review, later dismissed

2019-12-04 14:49 UTC, ademarco requested changes
Aren't there more templates where we use cards?

![image](https://user-images.githubusercontent.com/153362/70152455-8719f500-16ad-11ea-990f-60337777fbe4.png)

2019-12-10 18:59 UTC, ademarco approved these changes

2019-12-11 08:56 UTC, nagyad approved these changes

2019-12-11 08:56 UTC, merged