OPENEUROPA-2606: Render optional link of Social media follow paragraph.
openeuropa/oe_theme pull request #391
Opened 2019-12-06 13:24 UTC by 22Alexandra

## OPENEUROPA-2606

### Description

Render optional link of Social media follow paragraph.

### Change log

- Added: optional link field
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh

```

2019-12-10 16:24 UTC, imanoleguskiza requested changes

2019-12-10 16:24 UTC, imanoleguskiza commented on oe_theme.theme
> +    $variables['links'][$key + 1]['label'] = $other_link[0]['title'];
Why not let php set the index? $variables['links'][]

2019-12-10 16:24 UTC, imanoleguskiza commented on oe_theme.theme
> +    $other_link = $paragraph->get('field_oe_social_media_see_more')->getValue();
$paragraph->get('field_oe_social_media_see_more')->first()->getValue() would be better in this case I believe.

2019-12-10 16:24 UTC, imanoleguskiza commented on templates/patterns/social_media_links/pattern-social-media-links-horizontal.html.twig
> +    {% set _links = _links|merge([{
Instead of duplicating the code, set a link variable with this values and then if _link.service is set, add the icon information.

2019-12-11 10:55 UTC, imanoleguskiza submitted a review, later dismissed

2019-12-12 09:14 UTC, nagyad requested changes

2019-12-12 09:14 UTC, nagyad commented on oe_theme.theme
> +  if (!empty($paragraph->get('field_oe_social_media_see_more')->first()->getValue())) {
We should use $paragraph->get('field_oe_social_media_see_more')->isEmpty().

2019-12-12 09:17 UTC, nagyad commented
Needs rebase.

2019-12-12 12:40 UTC, nagyad submitted a review, later dismissed

2019-12-12 14:25 UTC, imanoleguskiza submitted a review, later dismissed

2019-12-12 14:50 UTC, imanoleguskiza approved these changes

2019-12-12 14:51 UTC, nagyad approved these changes

2019-12-12 14:51 UTC, merged