OPENEUROPA-2642: [oe_theme] Create a formatter for address field.
openeuropa/oe_theme pull request #396
Opened 2019-12-17 11:30 UTC by sergepavle

## OPENEUROPA-2642

### Description

It turned out that the address_plain formatter does not pass the entity to the theme function, making it impossible to create the proper suggestions. The only option left here is to create a custom formatter for the address field that will allow us to configure a separator and will print the address simply separated by that, like: Rue de la Loi, 56, 1000, Brussels.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2019-12-19 13:36 UTC, nagyad requested changes
Good job, just minor remarks.

2019-12-19 13:36 UTC, nagyad commented on modules/oe_theme_helper/src/Plugin/Field/FieldFormatter/AddressCustomFormatter.php
> + *   label = @Translation("Custom"),
Please change the label to something more descriptive such as "Inline address".

2019-12-19 13:36 UTC, nagyad commented on modules/oe_theme_helper/src/Plugin/Field/FieldFormatter/AddressCustomFormatter.php
> + *   id = "address_custom",
Let's call this oe_address_inline.

2019-12-19 13:36 UTC, nagyad commented on modules/oe_theme_helper/templates/address-custom.html.twig
> + * Default template for the 'custom' address formatter.
Let's rename this twig to oe_address_inline

2019-12-19 13:36 UTC, nagyad commented on modules/oe_theme_helper/tests/src/Kernel/Plugin/Field/FieldFormatter/AddressCustomFormatterTest.php
> +class AddressCustomFormatterTest extends FormatterTestBase {
AddressInlineFormatterTest

2019-12-23 12:43 UTC, nagyad approved these changes
Tested and it works as designed. Good job.

2020-01-06 10:09 UTC, 22Alexandra approved these changes

2020-01-06 10:11 UTC, merged