OPENEUROPA-2693: On IE11 the icons are not displayed.
openeuropa/oe_theme pull request #397
Opened 2019-12-23 16:20 UTC by sergepavle

## OPENEUROPA-2693

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-01-06 08:12 UTC, 22Alexandra submitted a review, later dismissed

2020-01-07 10:34 UTC, brummbar requested changes
Note from @ademarco: let's add the npm package `svg4everybody` as dependency, and then use the ecl-builder to copy it over in the dist package instead of putting the library file here.

2020-01-07 10:34 UTC, brummbar commented on js/svg4ie.js
> +(function (ECL, Drupal) {
No need to have ECL as parameter.

2020-01-07 10:34 UTC, brummbar commented on js/svg4ie.js
> +      if (typeof svg4everybody === "function" && !!navigator.userAgent.match(/Trident.*rv\:11\./)) {
No need to test that `svg4everybody` is defined, we already set the dependency.
Also no need to test for browser, the library does it already.

2020-01-07 10:34 UTC, brummbar commented on oe_theme.libraries.yml
> +    js/svg4ie.js: { preprocess: false }
Why disabling the aggregation on this script?

2020-01-07 10:34 UTC, brummbar commented on oe_theme.libraries.yml
> +    js/svg4ie.js: { preprocess: false }
Same as above.

2020-01-07 10:34 UTC, brummbar commented on oe_theme.libraries.yml
> +svg4everybody:
To know which version of the library we included, let's use the version here.

2020-01-07 10:34 UTC, brummbar commented on oe_theme.libraries.yml
> +    js/svg4everybody.min.js: { preprocess: false }
Also here, why disabling aggregation?

2020-01-07 10:36 UTC, brummbar commented on oe_theme.libraries.yml
> +svg4everybody:
This is not needed anymore, as we will use npm to handle the library.

2020-01-07 10:39 UTC, brummbar commented on js/svg4ie.js
> +      if (typeof svg4everybody === "function" && !!navigator.userAgent.match(/Trident.*rv\:11\./)) {
Since we won't be testing for browser, let's remove the `IE` stuff. It's just `svg4Everybody` the behavior name now.

2020-01-07 10:48 UTC, ademarco requested changes
I'd declare one single library as such:
```yml
external_svg:
  js:
    dist/js/svg4everybody.min.js: { minified: true }
    js/external_svg.js: {}
```
And then we can simply load this library via the hteme info.yml file, as we do with the `editor` library:

```yml
libraries:
  - oe_theme/editor
  - oe_theme/external_svg
```

2020-01-08 11:36 UTC, sergepavle commented on oe_theme.libraries.yml
> +    js/svg4ie.js: { preprocess: false }
Left over on try to fix order of js files.
Removed.

2020-01-09 10:39 UTC, brummbar requested changes

2020-01-09 10:39 UTC, brummbar commented on js/external_svg.js
> +    attach: function attach() {
Missed this last time: no need to name the function.
```suggestion
    attach: function () {
```

2020-01-09 10:39 UTC, brummbar commented on ecl-builder.config.js
> +    { from: path.resolve(nodeModules, 'svg4everybody/dist'), to: path.resolve(outputFolder, 'dist/js') },
Let's copy only the minified version of the script.

2020-01-09 10:39 UTC, brummbar commented on oe_theme.libraries.yml
> +    dist/js/svg4everybody.js: {}
So here we put the minified version.

2020-01-09 12:19 UTC, brummbar approved these changes

2020-01-09 16:01 UTC, ademarco approved these changes

2020-01-09 16:01 UTC, merged