OPENEUROPA-2221: Theme event content type
openeuropa/oe_theme pull request #404
Opened 2020-01-20 09:36 UTC by ademarco

2020-02-03 13:02 UTC, brummbar requested changes

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/README.md
> +    This section is accompanied by the featured media and it's legend. Read more about [auto placeholdering](https://www.drupal.org/docs/8/api/render-api/auto-placeholdering) with lazy builders.
```suggestion
    This section is accompanied by the featured media and its legend. Read more about [auto placeholdering](https://www.drupal.org/docs/8/api/render-api/auto-placeholdering) with lazy builders.
```

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_entity/modules/oe_theme_content_entity_venue/oe_theme_content_entity_venue.info.yml
> +description: Companion module for the OE Content Entity module
This description is the same for all the submodules, shouldn't it here indicate which entity is companion for? E.g. venue.

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/DescriptionExtraField.php
> +    $event = new EventEntityDecorator(Node::load($id));
We should still use \Drupal::service() to get the storage service.

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/ContactsExtraField.php
> +      if ($item->entity->bundle() === 'oe_general') {
This code can be simplified by determining the key and then using the view() and cache methods.

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/DescriptionExtraField.php
> +   * ContactsExtraField constructor.
©️ 🍝

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/DescriptionExtraField.php
> +    $cacheability = new CacheableMetadata();
This can be removed, see below.

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/DescriptionExtraField.php
> +      $cacheability->addCacheableDependency($entity->get('oe_event_featured_media')->entity)
```
CacheableMetadata::createFromObject($entity->get('oe_event_featured_media')->entity)
  ->applyTo($build);
```

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/DescriptionExtraField.php
> +    $renderable = $this->viewBuilder->viewField($entity->get('oe_event_featured_media'), [
Why this? Can't we extract it from `$entity->get('oe_event_featured_media')->first()`?

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/DetailsExtraField.php
> +   * ContactsExtraField constructor.
©️ 🍝

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/DetailsExtraField.php
> +      $configuration, $plugin_id, $plugin_definition,
This should be on multiple lines.

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/OrganiserExtraField.php
> +    if ($is_internal && !$entity->get('oe_event_organiser_internal')->isEmpty()) {
Let's return early. If it's empty we are not rendering anything.

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/OrganiserExtraField.php
> +    $is_internal = (int) $entity->get('oe_event_organiser_is_internal')->value === 1;
Shouldn't it be bool?

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/DescriptionExtraField.php
> +    // If we are past the end date and an event report is available, show it.
We can simplify this code by determining which field to use, and then pass it to the view builder part as variable. So we deduplicate the code.
```
$field = $event->isOver($now) && !$event->get('oe_event_report_text')->isEmpty()
  ? 'oe_event_report_text' : 
  : 'body';

return $view_builder->viewField($event->get($field), [
  'label' => 'hidden',
]);
```

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/RegistrationButtonExtraField.php
> +      '#url' => $url[0]['#url']->toString(),
We shouldn't rely on the url coming from the render array, we can fetch it from the field itself no?

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/RegistrationButtonExtraField.php
> +   * properly handled.
Uhm, I narrowed it down to just `\Drupal\datetime\Plugin\Field\FieldFormatter\DateTimeFormatterBase::formatDate()`, which uses the date formatter. Maybe I'm missing something.

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_helper/src/Plugin/field_group/FieldGroupFormatter/FieldListPattern.php
> +        'label' => isset($element[$field_name]['#title']) ? $element[$field_name]['#title'] : '',
```suggestion
        'label' => $element[$field_name]['#title'] ?? '',
```

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_helper/tests/src/Functional/Plugin/field_group/PatternFormatterTest.php
> +    // Create content type, with underscores.
#doubt

2020-02-03 13:02 UTC, brummbar commented on runner.yml.dist
> +    - "./vendor/bin/drush en field_ui -y"
Is it really needed field_ui?

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_entity/oe_theme_content_entity.info.yml
> +name: OpenEuropa Theme Content Entity
Why we made this as a module? No other modules depend on it and it doesn't have code.

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_entity/oe_theme_content_entity.info.yml
> +name: OpenEuropa Theme Content Entity
Leave this, but add dependencies to the sub modules.

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/DetailsExtraField.php
> +    $venue = $entity->get('oe_event_venue')->entity;
Venue field can be empty.

2020-02-03 13:02 UTC, brummbar commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/DetailsExtraField.php
> +      return [];
Handle address emptiness as instructed by extra_field module.

2020-02-03 15:55 UTC, ademarco commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/OrganiserExtraField.php
> +    if ($is_internal && !$entity->get('oe_event_organiser_internal')->isEmpty()) {
Not sure we can return early, both conditions are really dependent by the value of `$is_internal`. I'll add cacheable dependency to the first though, as we are accessing an entity.

2020-02-03 16:11 UTC, ademarco commented on runner.yml.dist
> +    - "./vendor/bin/drush en field_ui -y"
It's useful to have it enabled when working with entity displays.

2020-02-03 16:20 UTC, ademarco commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/RegistrationButtonExtraField.php
> +   * properly handled.
Right!

2020-02-13 11:38 UTC, ademarco commented on tests/Behat/DrupalContext.php
> +    return array_shift($entity_list);
We can use the content trait here?

2020-02-24 15:34 UTC, ademarco commented
Closing this in favor of #437, see OPENEUROPA-2774 for more info.

2020-02-24 15:34 UTC, closed without merging