OPENEUROPA-3009: Update ECL version.
openeuropa/oe_theme pull request #443
Opened 2020-03-12 16:25 UTC by sergepavle

## OPENEUROPA-OPENEUROPA-3009
### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-03-16 08:42 UTC, 22Alexandra submitted a review, later dismissed

2020-03-17 14:50 UTC, nagyad commented
I found this on the components page:
![image](https://user-images.githubusercontent.com/22004498/76868293-f84d7480-6866-11ea-99f4-3723989f4f62.png)

2020-03-17 15:04 UTC, nagyad requested changes
Rejecting due to missing styles for certain button variants.

2020-03-17 15:38 UTC, ademarco commented
It seems that this is not related to upgrade to 2.25, we already had it, I'll fix it anyway as it is perceived as a bug.

2020-03-17 16:03 UTC, ademarco submitted a review, later dismissed

2020-03-17 16:53 UTC, ademarco approved these changes

2020-03-18 08:19 UTC, nagyad approved these changes

2020-03-18 08:25 UTC, merged