OPENEUROPA-2988: Upgrade PHP version.
openeuropa/oe_theme pull request #448
Opened 2020-03-19 15:26 UTC by nagyad

2020-03-20 08:33 UTC, imanoleguskiza submitted a review, later dismissed

2020-03-20 11:23 UTC, brummbar requested changes

2020-03-20 11:23 UTC, brummbar commented on README.md
> -- The European Union footer, shipping with a set of links and references that must be present on all European Union sites.
The empty spaces at the end of the lines are to enforce a line break in markdown. We need to restore them.

2020-03-23 11:12 UTC, brummbar requested changes

2020-03-23 11:12 UTC, brummbar commented on README.md
> +* [PHP 7.3](http://php.net/)
It actually depends on 7.2 or 7.3

2020-03-23 16:10 UTC, brummbar approved these changes

2020-03-24 08:29 UTC, imanoleguskiza approved these changes

2020-03-24 08:30 UTC, merged