OPENEUROPA-3052: Remove ecl-editor wrapper from timeline tpl.
openeuropa/oe_theme pull request #449
Opened 2020-03-23 15:15 UTC by 22Alexandra

## OPENEUROPA-3052

### Description

Remove ecl-editor wrapper from timeline tpl.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-03-24 10:54 UTC, nagyad submitted a review, later dismissed

2020-03-24 16:58 UTC, ademarco requested changes
This will prevent HTML in content field to be styled correctly.

2020-03-25 08:38 UTC, ademarco commented
To fix it we need to wrap each description with `ecl-editor` as timeline expects single elements to receive ECL classes in order to be properly styled (like `ecl-link`).

![image](https://user-images.githubusercontent.com/153362/77517390-550ae980-6e7c-11ea-8534-94238bdde857.png)

2020-03-25 12:49 UTC, ademarco approved these changes

2020-03-25 13:12 UTC, nagyad approved these changes

2020-03-25 13:12 UTC, merged