OPENEUROPA-3091: Adapt banner preprocess for optional link.
openeuropa/oe_theme pull request #465
Opened 2020-04-20 08:49 UTC by 22Alexandra

2020-04-20 12:33 UTC, nagyad submitted a review, later dismissed

2020-04-20 15:26 UTC, nagyad submitted a review, later dismissed

2020-04-21 08:39 UTC, imanoleguskiza requested changes

2020-04-21 08:39 UTC, imanoleguskiza commented on templates/patterns/banners/pattern-banner-hero.html.twig
> +{% if url is not empty and label is not empty %}
We can simplify this like this: 

```
{% if url is not empty and label is not empty %}
  {% set _link = {'link' : {'path' : url, 'label' : label, icon_position: 'after'}} -%}
  {% set _link = _link|merge({'icon' : {'path' : ecl_icon_path, 'type' : "ui", 'name' : "corner-arrow", 'transform' : "rotate-90", 'size' : "xs"}}) %}
{% endif %}
```
That way we don't need to declare link_

2020-04-21 09:37 UTC, imanoleguskiza submitted a review, later dismissed

2020-04-21 09:39 UTC, nagyad submitted a review, later dismissed

2020-04-26 18:26 UTC, imanoleguskiza approved these changes

2020-04-27 07:35 UTC, nagyad approved these changes

2020-04-27 12:57 UTC, merged