OPENEUROPA-2068: Hide icon field for Accordion item paragraph.
openeuropa/oe_theme pull request #492
Opened 2020-06-02 09:16 UTC by 22Alexandra

2020-06-03 08:06 UTC, sergepavle submitted a review, later dismissed

2020-06-03 16:40 UTC, brummbar requested changes

2020-06-03 16:40 UTC, brummbar commented on modules/oe_theme_helper/oe_theme_helper.module
> +  unset($element['subform']['field_oe_icon']);
We should set the access to FALSE and also check if the field exists at all. It could be removed from the form display.

2020-06-03 16:40 UTC, brummbar commented on tests/Functional/ParagraphsTest.php
> + * Tests that theme configuration is correctly applied.
©️ 🍝

2020-06-03 16:40 UTC, brummbar commented on tests/Functional/ParagraphsTest.php
> +    $this->assertSession()->elementExists('css', '.field--name-field-oe-text');
We can use fieldExists().

2020-06-03 16:40 UTC, brummbar commented on tests/Functional/ParagraphsTest.php
> +  public static $modules = [
This should be protected, see the base class.

2020-06-03 16:40 UTC, brummbar commented on tests/Functional/ParagraphsTest.php
> +  public function testAccordionParagraph(): void {
The description says we test the item, but it's not reflected in the function name.

2020-06-05 08:36 UTC, brummbar approved these changes

2020-06-05 08:38 UTC, sergepavle approved these changes

2020-06-05 08:43 UTC, merged