OPENEUROPA-3290: Sort menu local tasks by weight.
openeuropa/oe_theme pull request #512
Opened 2020-07-06 16:47 UTC by 22Alexandra

2020-07-07 07:55 UTC, nagyad submitted a review, later dismissed

2020-07-09 08:28 UTC, upchuk requested changes

2020-07-09 08:28 UTC, upchuk commented on tests/Kernel/MenuLocalTasksTest.php
> +            'title' => 'Middle link',
If you named this one Middle link, add to the other ones as well "First" and "Second" to the name to indicate their extra purpose in the list.

2020-07-09 08:36 UTC, upchuk approved these changes

2020-07-09 08:37 UTC, brummbar approved these changes

2020-07-09 08:55 UTC, merged