OPENEUROPA-2622: Add 'Location' field type and add 'Project locations' field to Project content type.
openeuropa/oe_theme pull request #549
Opened 2020-08-27 11:10 UTC by yenyasinn

## OPENEUROPA-2622

### Description

Project locations field has been added to Project CT.

2020-08-27 11:13 UTC, yenyasinn commented on tests/Functional/ContentProjectRenderTest.php
> +      'oe_project_locations' => [
It looks a little bit different than on the mockup. Address field doesn't provide regions "Bavaria", or "Brussels".

<img width="761" alt="Screenshot 2020-08-27 at 12 51 46" src="https://user-images.githubusercontent.com/1183951/91435577-31a2fb00-e86f-11ea-82f4-bf7b54a6344f.png">

2020-08-28 09:48 UTC, nagyad approved these changes

2020-08-28 11:34 UTC, nagyad requested changes
Missing address module from dependencies.

2020-08-31 07:54 UTC, yenyasinn commented
> Missing address module from dependencies.

Address module dependency has been added to oe_content_project module.

2020-08-31 10:25 UTC, ademarco approved these changes

2020-08-31 10:32 UTC, nagyad approved these changes

2020-08-31 11:27 UTC, merged