EWPP-191: File teaser pattern.
openeuropa/oe_theme pull request #551
Opened 2020-08-31 12:47 UTC by 22Alexandra

2020-09-07 10:46 UTC, ademarco requested changes
I've removed the teaser from the file value object, as it wasn't supposed to be part of that, and pushed my change. We still have one thing to fix.

2020-09-07 10:46 UTC, ademarco commented on tests/Kernel/fixtures/rendering.yml
> +      'footer.ecl-card__footer': 1
We shouldn't change this test, if footer is not set then we shouldn't have it displayed. Maybe this was a regression in ecl twing, in which case we need to patch the related component in order to make sure that the original version of this test passes.

2020-09-07 13:06 UTC, ademarco submitted a review, later dismissed

2020-09-07 14:18 UTC, imanoleguskiza approved these changes, later dismissed

2020-09-07 14:40 UTC, imanoleguskiza submitted a review, later dismissed

2020-09-07 14:52 UTC, nagyad submitted a review, later dismissed

2020-09-07 14:52 UTC, nagyad commented on composer.json
> +        "openeuropa/code-review": "~1.5.0",
Patch number should not be there.

2020-09-07 15:02 UTC, imanoleguskiza approved these changes

2020-09-08 06:41 UTC, ademarco approved these changes

2020-09-08 06:42 UTC, merged