EWPP-208: Integrate new ECL multiple select widget
openeuropa/oe_theme pull request #554
Opened 2020-09-01 13:12 UTC by imanoleguskiza

## OPENEUROPA-208

### Description

Integrate new ECL multiple select widget

### Change log

- Added:
- Changed: Update select template to Integrate new ECL multiple select widget
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-09-07 09:01 UTC, ademarco requested changes

2020-09-07 09:01 UTC, ademarco commented on tests/modules/oe_theme_js_test/src/Form/MultiSelectTestForm.php
> +          ->t('Three'),
Can't we put all of these on the same line? :smile:

```
$this->t('Two point two'),
```

2020-09-07 09:01 UTC, ademarco commented on templates/form/select.html.twig
> +  {% set attributes = attributes.setAttribute('data-ecl-select-all', 'Select all') %}
We need to wrap all label strings to `t()`

2020-09-18 11:44 UTC, upchuk submitted a review, later dismissed

2020-09-22 10:40 UTC, ademarco approved these changes

2020-09-22 10:41 UTC, upchuk approved these changes

2020-09-22 10:41 UTC, merged