EWPP-192: Add translation toggle label variable to file patterns.
openeuropa/oe_theme pull request #568
Opened 2020-09-10 15:47 UTC by 22Alexandra

2020-09-15 14:19 UTC, ademarco reviewed
Only one comment, rest is ok, haven't tested it manually though.

2020-09-15 14:19 UTC, ademarco commented on templates/patterns/file_teaser/pattern-file-teaser.html.twig
> +      'label': translation_toggle_label ~ " (@count)"|t({ '@count': translations|length}),
Let's simply concatenate this string, not passing via t()
```suggestion
      'label': translation_toggle_label ~ " (" ~ translations|length ~ ")",
```

Same below

2020-09-16 08:50 UTC, ademarco requested changes

2020-09-16 08:50 UTC, ademarco commented on templates/patterns/file_teaser/pattern-file-teaser.html.twig
> +      'label': translation_toggle_label ~ " (" ~ translations|length ~ ")",
In order to make this backward compatible, i.e. when people are using patterns that don't have the new field set, let's do this:
```suggestion
      'label': translation_toggle_label|default("Available translations"|t) ~ " (" ~ translations|length ~ ")",
```

2020-09-16 08:50 UTC, ademarco commented on templates/patterns/file_translation/pattern-file-translation.html.twig
> +      'label': translation_toggle_label ~ " (" ~ translations|length ~ ")",
same remark as above.

2020-09-16 09:44 UTC, imanoleguskiza approved these changes

2020-09-16 09:51 UTC, ademarco approved these changes

2020-09-16 10:14 UTC, merged