EWPP-278: Update ECL components to 2.33.
openeuropa/oe_theme pull request #581
Opened 2020-09-17 13:38 UTC by imanoleguskiza

## OPENEUROPA-278
### Description

Update ECL components to 2.33.

### Change log

- Added:
- Changed: Update ECL components to 2.33.
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-09-17 14:14 UTC, ademarco requested changes

2020-09-17 14:14 UTC, ademarco commented on package.json
>      "@ecl-twig/ec-components": "2.32.0",
We need to upgrade ecl-twig too.

2020-09-17 14:40 UTC, ademarco commented on package.json
>      "@ecl-twig/ec-components": "2.32.0",
We will actually update ECL only now and open a follow up for ecl twig. We spoke with ECL maintainer and the changes in ECL are actually only on CSS and JS and they block an important ticket (search widget).

@imanoleguskiza will open a follow up for ecl twig.

2020-09-17 14:41 UTC, ademarco submitted a review, later dismissed

2020-09-18 09:33 UTC, 22Alexandra approved these changes

2020-09-18 10:50 UTC, ademarco approved these changes

2020-09-18 10:50 UTC, merged