EWPP-328: Theme date and datepicker using ecl.
openeuropa/oe_theme pull request #606
Opened 2020-09-30 12:18 UTC by drishu

## EWPP-328

### Description

Theme date and datepicker using ecl.

### Change log

- Added:
   - templates for date & time
   - theme suggestion for time input
   - datepicker ecl component

2020-10-01 13:48 UTC, imanoleguskiza requested changes

2020-10-01 13:48 UTC, imanoleguskiza commented on oe_theme.theme
> +  $php_date_format = $variables['#attributes']['data-drupal-date-format'] ?? 'Y-m-d';
There is no key #attributes, just attributes, and the value of data-drupal-date-format seems to be an array, so we always end up using the default Y-m-d

2020-10-01 13:48 UTC, imanoleguskiza commented on templates/form/input--date.html.twig
> +  placeholder: 'DD-MM-YYYY'
This value should be the same as the value we send to the datepicker js.

2020-10-01 13:50 UTC, upchuk commented on templates/form/input--date.html.twig
> +  placeholder: 'DD-MM-YYYY'
@imanoleguskiza preprocess this please so it takes it also dynamically like the component for the format.

2020-10-02 07:28 UTC, imanoleguskiza approved these changes, later dismissed

2020-10-02 08:03 UTC, 22Alexandra approved these changes

2020-10-02 08:03 UTC, imanoleguskiza approved these changes

2020-10-02 08:35 UTC, merged