EWPP-337: Update pattern list item image background styles.
openeuropa/oe_theme pull request #616
Opened 2020-10-05 14:09 UTC by 22Alexandra

2020-10-06 07:06 UTC, nagyad submitted a review, later dismissed

2020-10-06 10:34 UTC, imanoleguskiza submitted a review, later dismissed

2020-10-07 05:34 UTC, ademarco requested changes
Not sure this will work guys, we get a space here if image format is not complying with the container ratio. Maybe we should also center the backgound?

![image](https://user-images.githubusercontent.com/153362/95291292-7f981f00-086f-11eb-8f33-692537cab291.png)

2020-10-07 05:47 UTC, ademarco approved these changes
This now looks like that, approving.

![image](https://user-images.githubusercontent.com/153362/95292218-56788e00-0871-11eb-9f1d-6544853eaf0a.png)

2020-10-07 06:30 UTC, upchuk approved these changes

2020-10-07 06:35 UTC, merged