EWPP-371: Add checks when adding region suggestions for blocks.
openeuropa/oe_theme pull request #630
Opened 2020-10-19 13:29 UTC by imanoleguskiza

## EWPP-371

### Description

Add checks when adding region suggestions for blocks.

### Change log

- Added:
- Changed: Add checks when adding region suggestions for blocks.
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-10-19 13:47 UTC, nagyad approved these changes, later dismissed

2020-10-20 07:11 UTC, ademarco requested changes

2020-10-20 07:11 UTC, ademarco commented on oe_theme.theme
> +  if(!$block) {
```suggestion
  if(!$block instanceof BlockInterface) {
```
So we have an extra layer of security there.

2020-10-20 08:17 UTC, ademarco approved these changes

2020-10-20 08:34 UTC, nagyad approved these changes

2020-10-20 10:04 UTC, merged