EWPP-544: Render file patterns only when file is set.
openeuropa/oe_theme pull request #650
Opened 2020-11-23 10:24 UTC by 22Alexandra

2020-11-24 09:31 UTC, sergepavle requested changes
I've left a few comments.

2020-11-24 09:31 UTC, sergepavle commented on src/DocumentMediaValueExtractor.php
> +    if ($media->get('oe_media_remote_file')->first()->getSize() == 0) {
===

2020-11-24 09:31 UTC, sergepavle commented on src/DocumentMediaValueExtractor.php
> +    if ($media->get('oe_media_remote_file')->first()->getSize() == 0) {
We can reuse $file_link variable.

2020-11-24 09:31 UTC, sergepavle commented on templates/content/media--document--default.html.twig
> +{% if file is not empty %}
We can drop `is not empty`. Everything else will be handled by twig.

2020-11-24 10:02 UTC, sergepavle submitted a review, later dismissed

2020-11-24 11:45 UTC, sergepavle submitted a review, later dismissed

2020-11-26 14:04 UTC, upchuk approved these changes

2020-11-26 14:09 UTC, sergepavle approved these changes

2020-11-26 14:09 UTC, sergepavle approved these changes

2020-11-26 14:10 UTC, merged