EWPP-468: Add site-specific other links to corporate footers.
openeuropa/oe_theme pull request #653
Opened 2020-11-24 13:09 UTC by drishu

## EWPP-468

### Description

Add site-specific other links to corporate footers.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-11-25 12:35 UTC, georgebaev reviewed
@drishu I found the following misalignment for a specific configuration of footer links:
![image](https://user-images.githubusercontent.com/120784/100228051-c5499d80-2f2a-11eb-8190-73beb2f67bc0.png)
![image](https://user-images.githubusercontent.com/120784/100228178-f75aff80-2f2a-11eb-9148-d005b7005322.png)
Please see how the `Related sites` section is not top-aligned with the `Contact us` section. 

I am not sure if this misalignment is relevant to this PR's functionality

2020-11-25 13:00 UTC, ademarco requested changes
So when there are 3 sections and the only filled in one is not the first, and we have no social links:

![image](https://user-images.githubusercontent.com/153362/100230616-389ce080-2f26-11eb-9e1c-ed2c34d807ff.png)

Then this happens: 

![image](https://user-images.githubusercontent.com/153362/100230544-23c04d00-2f26-11eb-9c66-9845a5d175d3.png)

I think we need to remove empty sections, so initially related links will be on top of social links.

Or, we keep the way it is now, so related links will always be on the right, unless there are no social links, in which case we don't bother.

I think we need to involve @kugta

2020-11-25 13:11 UTC, ademarco commented
@drishu actually checking the empty behaviour here: https://ec.europa.eu/component-library/playground/ec/?path=/story/components-footers-standardised--default 

Let's make sure that when we don't have the left column, the right column is displayed on the left:

![Peek 2020-11-25 14-09](https://user-images.githubusercontent.com/153362/100231839-d80ea300-2f27-11eb-9f3d-8d435180ec66.gif)

Also mind the top margin, we get this now because we print empty sections.

![image](https://user-images.githubusercontent.com/153362/100231980-08564180-2f28-11eb-9601-f8ce4942954c.png)

2020-11-26 09:33 UTC, georgebaev commented on templates/navigation/oe-corporate-blocks-ec-footer--standardised.html.twig
> +  {# Follow section must always be the last on on the left. #}
There is a double "on" in the comment

2020-11-26 09:41 UTC, georgebaev commented on templates/navigation/oe-corporate-blocks-eu-footer--standardised.html.twig
> +  {# Follow section must always be the last on on the left. #}
There is a double "on" in the comment.

2020-11-26 10:56 UTC, georgebaev submitted a review, later dismissed

2020-11-26 17:00 UTC, 22Alexandra submitted a review, later dismissed

2020-11-27 13:14 UTC, ademarco approved these changes, later dismissed

2020-11-27 13:41 UTC, ademarco approved these changes

2020-11-27 13:44 UTC, georgebaev approved these changes

2020-11-27 14:05 UTC, merged