EWPP-485: Adjust selectors for behat tests.
openeuropa/oe_theme pull request #657
Opened 2020-11-26 11:25 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-11-27 13:47 UTC, drishu approved these changes, later dismissed

2020-11-30 13:20 UTC, drishu requested changes
I think this branch, for now, should use 
`"openeuropa/oe_corporate_blocks": "dev-EWPP-485 as 3.x-dev"`
so we can see it together.
without this, the upgrade test fails with whitescreen.

2020-11-30 18:38 UTC, sergepavle commented
> I think this branch, for now, should use
> `"openeuropa/oe_corporate_blocks": "dev-EWPP-485 as 3.x-dev"`
> so we can see it together.
> without this, the upgrade test fails with whitescreen.

I wouldn't overcomplicate chains of PR. Main PR already exists for ewcms. So any changes in oe_corporate_blocks will be visible in PR for ewcms.

2020-11-30 18:41 UTC, drishu approved these changes

2020-12-01 09:22 UTC, ademarco approved these changes

2020-12-01 09:22 UTC, merged