EWPP-418: Render webtools op publication list media using media container.
openeuropa/oe_theme pull request #675
Opened 2020-12-08 07:46 UTC by 22Alexandra

2020-12-08 18:30 UTC, sergepavle commented on tests/Kernel/MediaRenderTest.php
> +   * Tests Webtools Op Publication List media rendering.
```suggestion
   * Tests Webtools OP Publication List media rendering.
```

2020-12-08 18:30 UTC, sergepavle commented on tests/Kernel/MediaRenderTest.php
> +    // Create a op publication list media.
```suggestion
    // Create a OP Publication list media.
```

2020-12-09 08:15 UTC, sergepavle approved these changes, later dismissed

2020-12-14 09:33 UTC, brummbar requested changes

2020-12-14 09:33 UTC, brummbar commented on tests/Kernel/MediaRenderTest.php
> +    $this->assertCount(1, $crawler->filter('div.ecl-media-container__media.ecl-media-container__media--ratio-16-9'));
Test that the JSON is inside the rendered html.

2020-12-14 12:19 UTC, nagyad submitted a review, later dismissed

2020-12-14 12:20 UTC, nagyad commented
Approved, still 417 needs to go in before.

2020-12-15 09:53 UTC, brummbar approved these changes, later dismissed

2020-12-15 16:17 UTC, imanoleguskiza submitted a review, later dismissed

2020-12-16 08:20 UTC, imanoleguskiza approved these changes

2020-12-16 08:23 UTC, brummbar approved these changes

2020-12-16 08:28 UTC, merged