EWPP-631: Fix double encoding of html entities.
openeuropa/oe_theme pull request #699
Opened 2021-01-14 17:03 UTC by drishu

## EWPP-631

### Description

Fix double encoding of html entities.

### Change log

- Changed: AddressInlineFormatter
- Fixed: Fix double encoding of html entities.

2021-01-15 11:14 UTC, sergepavle requested changes

2021-01-15 11:14 UTC, sergepavle commented on modules/oe_theme_helper/src/Plugin/Field/FieldFormatter/AddressInlineFormatter.php
> +      drupal_set_message($field);
Leftover after debugging?

2021-01-15 11:14 UTC, sergepavle commented on modules/oe_theme_helper/tests/src/Kernel/Plugin/Field/FieldFormatter/AddressInlineFormatterTest.php
> +      'address_line1' => 'Rue de la Loi, 56 <123>',
It would be nice to have also tests for single and double-quotes.

2021-01-18 09:01 UTC, drishu commented on modules/oe_theme_helper/src/Plugin/Field/FieldFormatter/AddressInlineFormatter.php
> +      drupal_set_message($field);
ups

2021-01-18 17:24 UTC, sergepavle submitted a review, later dismissed

2021-01-20 10:58 UTC, georgebaev submitted a review, later dismissed

2021-01-25 19:49 UTC, sergepavle submitted a review, later dismissed

2021-01-26 11:25 UTC, sergepavle submitted a review, later dismissed

2021-01-26 11:48 UTC, georgebaev approved these changes, later dismissed

2021-02-02 11:49 UTC, ademarco submitted a review, later dismissed

2021-02-09 10:21 UTC, sergepavle commented on modules/oe_theme_helper/tests/src/Kernel/Plugin/Field/FieldFormatter/AddressInlineFormatterTest.php
>        'locality' => 'Brussels',
It would be nice to reflect in a test that the city also doesn't have anymore double escaping.

2021-02-09 15:42 UTC, sergepavle approved these changes

2021-02-10 08:22 UTC, ademarco approved these changes

2021-02-10 08:34 UTC, merged