EWPP-164: Remove duplicated processing code to style a Media entity using the ECL media container
openeuropa/oe_theme pull request #701
Opened 2021-01-16 11:39 UTC by drishu

## EWPP-164

### Description

Create a Media value object and a media container pattern to use it on oe_theme_preprocess_paragraph__oe_text_feature_media and featured media field formatter

### Change log

- Added: Media container pattern and Media Value object
- Changed: oe_theme_preprocess_paragraph__oe_text_feature_media and  featured media field formatter use now the media container pattern

2021-01-19 11:14 UTC, 22Alexandra submitted a review, later dismissed

2021-01-22 09:25 UTC, georgebaev approved these changes, later dismissed

2021-01-26 11:41 UTC, 22Alexandra approved these changes

2021-01-26 11:51 UTC, georgebaev approved these changes

2021-01-27 12:29 UTC, ademarco requested changes
This seems way to large of a refactoring, I'll block it for now, I'll have to have a look at it.

2025-06-09 09:30 UTC, closed without merging