EWPP-614: Set labels in teaser view mode to be hidden.
openeuropa/oe_theme pull request #715
Opened 2021-01-26 13:46 UTC by nagyad

2021-01-26 15:35 UTC, ademarco requested changes

2021-01-26 15:35 UTC, ademarco commented on modules/oe_theme_content_publication/oe_theme_content_publication.post_update.php
> +    $display->setComponent($field, $component);
On a site we cannot assume these fields are on the teaser, we need to check that they are before changing the label.

2021-01-26 15:35 UTC, ademarco commented on modules/oe_theme_content_publication/oe_theme_content_publication.post_update.php
> +  $display = EntityViewDisplay::load('node.oe_publication.teaser');
We cannot assume that the teaser is still there on a site using this module, let's first check that it exists.

2021-01-26 15:57 UTC, ademarco approved these changes, later dismissed

2021-01-26 16:06 UTC, drishu approved these changes, later dismissed

2021-02-02 08:19 UTC, ademarco approved these changes

2021-02-02 08:21 UTC, drishu approved these changes

2021-02-02 08:22 UTC, merged