EWPP-722: Add theme suggestions for text fields to replace multiple field templates.
openeuropa/oe_theme pull request #721
Opened 2021-02-03 07:24 UTC by 22Alexandra

2021-02-03 18:06 UTC, sergepavle requested changes

2021-02-03 18:06 UTC, sergepavle commented on oe_theme.theme
> +
Those blocks of code look pretty similar, So looks like can be merged.
```suggestion
  if (in_array($element['#field_type'], ['entity_reference_revisions', 'text_long', 'text_with_summary'])) {
    /** @var \Drupal\field\Entity\FieldConfig $field_definition */
    $field_definition = $element['#items']->getFieldDefinition();
    // Add suggestions based on the parent entity and bundle types.
    $suggestions[] = 'field__' . $element['#field_type'] . '__' . $element['#entity_type'];
    $suggestions[] = 'field__' . $element['#field_type'] . '__' . $element['#entity_type'] . '__' . $element['#bundle'] . '__' . $field_definition->getName();
  }

```

2021-02-03 18:06 UTC, sergepavle commented on templates/field/field--text-long--node.html.twig
> +{#
Seems like a template for paragraph 'field--text-long--paragraph.html.twig' is missed (in this case we can remove more specific field--paragraph--field-oe-text-long.html.twig.

2021-02-03 18:06 UTC, sergepavle commented on templates/field/field--text-long--node.html.twig
> +{#
as I can see same we can do for oe-contact--full.html.twig. where we can also add config for oe_contact entity type.

2021-02-04 08:42 UTC, sergepavle requested changes
we can remove previous
https://github.com/openeuropa/oe_theme/pull/721/commits/ecb2c4f7fb2b732607235538b9035483305dc533#diff-14faf6dd33cb73959ac854a38b66b254211a2a19578daa194dba5385cd13d95dR173-R174

2021-02-04 11:34 UTC, sergepavle approved these changes, later dismissed

2021-02-10 08:34 UTC, drishu approved these changes

2021-02-15 08:29 UTC, ademarco requested changes

2021-02-15 08:29 UTC, ademarco commented on oe_theme.theme
> +  if (in_array($element['#field_type'], ['text_long', 'text_with_summary'])) {
Why only for those two field types? The issue is about providing theme suggestion for field types in general, then to be used for those two specific types.

2021-02-15 08:29 UTC, ademarco commented on templates/field/field--text-with-summary--node.html.twig
> +</div>
If we do this, then every field of type text with summary will be printed without label. This is true for all the rest too.

2021-02-16 09:55 UTC, drishu requested changes
For testing the changes we already check field of these types for ec-editor class in functional rendering tests, but to also test for labels I suggest we create a new GenericFieldsTest where we test fields of different types for ecl formatting, what do you think @ademarco ?

2021-02-22 18:57 UTC, ademarco commented on oe_theme.theme
> +    $suggestions[] = 'field__' . $element['#field_type'] . '__' . $element['#entity_type'];
Can we also add this below, so we don't have to specify the entity type?
```php
    $suggestions[] = 'field__' . $element['#field_type'];
```

2021-04-28 12:15 UTC, sergepavle submitted a review, later dismissed

2021-06-08 07:21 UTC, sergepavle approved these changes

2021-06-08 07:32 UTC, upchuk approved these changes

2021-06-08 07:59 UTC, ademarco approved these changes

2021-06-09 08:17 UTC, merged