EWPP-745: Add margin top to page header when breadcrumb is missing.
openeuropa/oe_theme pull request #723
Opened 2021-02-08 11:52 UTC by 22Alexandra

2021-02-08 16:10 UTC, sergepavle submitted a review, later dismissed

2021-02-09 07:33 UTC, upchuk requested changes
Approved from me, will merge with the entire epic.

2021-02-18 08:10 UTC, upchuk approved these changes

2021-02-18 08:33 UTC, imanoleguskiza approved these changes

2021-02-18 08:33 UTC, merged