EWPP-805: Create ECL Gallery field formatter for media fields
openeuropa/oe_theme pull request #739
Opened 2021-02-26 11:32 UTC by ademarco

2021-03-30 10:33 UTC, imanoleguskiza approved these changes

2021-03-31 09:56 UTC, imanoleguskiza requested changes

2021-03-31 09:56 UTC, imanoleguskiza commented on src/ValueObject/GalleryItemValueObject.php
> +   * IMage gallery item type.
Oh noes

2021-03-31 09:56 UTC, imanoleguskiza commented on src/ValueObject/ImageValueObjectInterface.php
> +interface ImageValueObjectInterface extends ValueObjectInterface {
Should we add a GalleryItemValueObjectInterface?

2021-04-07 12:28 UTC, imanoleguskiza approved these changes

2021-04-07 12:36 UTC, brummbar approved these changes

2021-04-07 12:36 UTC, merged