EWPP-812: Add heading to timeline pattern.
openeuropa/oe_theme pull request #755
Opened 2021-03-15 08:01 UTC by 22Alexandra

2021-03-15 13:14 UTC, upchuk requested changes

2021-03-15 13:14 UTC, upchuk commented on oe_theme.theme
> +  if (!$paragraph->get('field_oe_title')->isEmpty()) {
Let's put a check here if the field exists in case oe theme is updated while oe_paragraphs doesn't yet get the field on a site.

2021-03-15 13:21 UTC, upchuk requested changes
Approving but blocking the merge for the full epic.

2021-03-17 15:16 UTC, sergepavle requested changes

2021-03-17 15:16 UTC, sergepavle commented on tests/Kernel/fixtures/rendering.yml
> +      'h2.ecl-u-type-heading-2': 1
I think it would be nice in another test to check that we don't have this h2 in case the title is empty.

2021-03-17 17:08 UTC, sergepavle submitted a review, later dismissed

2021-03-25 13:31 UTC, sergepavle approved these changes

2021-03-25 13:44 UTC, upchuk approved these changes

2021-03-25 13:45 UTC, merged