EWPP-969: Move Social media links outside Media fieldgroup on Person full view display.
openeuropa/oe_theme pull request #776
Opened 2021-04-12 15:16 UTC by 22Alexandra

2021-04-13 15:28 UTC, imanoleguskiza requested changes

2021-04-13 15:28 UTC, imanoleguskiza commented on tests/Functional/ContentPersonRenderTest.php
> -    $inpage_nav_expected_values['list'][] = [
We removed this but we need to add it whenever we test the media items.

2021-04-14 09:59 UTC, imanoleguskiza approved these changes

2021-04-14 10:08 UTC, imanoleguskiza submitted a review, later dismissed

2021-04-14 11:31 UTC, ademarco requested changes, later dismissed
We need to provide an upgrade path to update the view mode, as the theme is already released.

2021-04-16 09:17 UTC, brummbar approved these changes
Blind

2021-04-16 09:18 UTC, imanoleguskiza approved these changes

2021-04-16 09:18 UTC, merged