EWPP-992: Update full display contacts rendering.
openeuropa/oe_theme pull request #782
Opened 2021-04-19 12:08 UTC by 22Alexandra

2021-04-20 06:30 UTC, upchuk requested changes

2021-04-20 06:30 UTC, upchuk commented on modules/oe_theme_content_organisation/src/Plugin/ExtraField/Display/TeaserDetailsExtraField.php
> +        return $build;
So if the first contact is not accessible, we return and don't continue the loop?

2021-04-20 06:30 UTC, upchuk commented on modules/oe_theme_content_organisation/src/Plugin/ExtraField/Display/TeaserDetailsExtraField.php
> +          $items[] = $this->getRenderableFieldListItem($contact, $field_name, $display_options);
You are merging here the fields of all the contacts and this is not what needs to happen if you look at the screenshot. 

I have two contacts:

![Screen Shot 2021-04-20 at 09 28 53](https://user-images.githubusercontent.com/5848933/115348082-7985e200-a1b2-11eb-9496-a4bc6cf36e5e.png)

And this is the resulting teaser:

![Screen Shot 2021-04-20 at 09 29 19](https://user-images.githubusercontent.com/5848933/115348127-87d3fe00-a1b2-11eb-92a2-f5ade5f9cf17.png)

Compare please to the screenshot from the ticket.

2021-04-20 08:44 UTC, upchuk requested changes

2021-04-20 08:44 UTC, upchuk commented on modules/oe_theme_content_organisation/src/Plugin/ExtraField/Display/TeaserDetailsExtraField.php
> -      $cache->applyTo($build);
Why are you applying the cache to the build here alreeady?

2021-04-20 08:44 UTC, upchuk commented on modules/oe_theme_content_organisation/src/Plugin/ExtraField/Display/TeaserDetailsExtraField.php
> +    foreach ($entity->get('oe_organisation_contact')->referencedEntities() as $key => $contact) {
as $delta

2021-04-20 08:49 UTC, upchuk approved these changes

2021-04-20 13:08 UTC, sergepavle commented on modules/oe_theme_content_organisation/src/Plugin/ExtraField/Display/TeaserDetailsExtraField.php
> +      if (!$contact) {
```suggestion
      if (!$contact instanceof ContactInterface) {
```

2021-04-20 13:14 UTC, sergepavle approved these changes

2021-04-21 11:07 UTC, sergepavle approved these changes

2021-04-21 12:32 UTC, merged