EWPP-989: Theme "Leadership and organisation" section.
openeuropa/oe_theme pull request #787
Opened 2021-04-22 09:04 UTC by 22Alexandra

2021-05-04 10:59 UTC, imanoleguskiza requested changes

2021-05-04 10:59 UTC, imanoleguskiza commented on templates/content/node--oe-person--oe-compact-teaser.html.twig
> +  <div role="img" class="ecl-u-flex-shrink-0 ecl-u-mr-s ecl-u-media-a-s ecl-u-media-bg-size-contain ecl-u-media-bg-repeat-none " style="background-image:url({{ content.portrait_image['#markup'] }})">
I don't think we need to use the #markup here

2021-05-04 10:59 UTC, imanoleguskiza commented on tests/Functional/ContentOrganisationRenderTest.php
> +use Drupal\node\Entity\Node;
There were many changes done in this class in this PR https://github.com/openeuropa/oe_theme/pull/629/files, might be  worth bringing the changes to the epic branch and rebasing this.

2021-05-04 13:37 UTC, imanoleguskiza commented on tests/Functional/ContentOrganisationRenderTest.php
> +use Drupal\node\Entity\Node;
We will do this once this is merged.

2021-05-04 15:12 UTC, imanoleguskiza submitted a review, later dismissed

2021-05-05 13:17 UTC, ademarco requested changes

2021-05-05 13:17 UTC, ademarco commented on modules/oe_theme_content_organisation/oe_theme_content_organisation.info.yml
> +  - oe_content:oe_content_organisation_person_reference
We need to enable this via a hook update now, since we removed it from the oe_content_organisation hook update / dependency.

2021-05-05 13:17 UTC, ademarco commented on templates/content/node--oe-person--oe-compact-teaser.html.twig
> +    <div class="ecl-content-item__meta ecl-u-type-s ecl-u-type-color-grey-75 ecl-u-mb-xs">{{ content.oe_person_jobs }}</div>
Do not print this div is no person jobs are there.

2021-05-05 13:17 UTC, ademarco commented on templates/field/field--node--oe-organisation-staff-link--oe-organisation--full.html.twig
> +        path: item.content['#url'],
By accessing link render array portions we don't allow cache to bubble up. The easiest way to fix it is to render the link and assign the output to a catch all variable, that will never be displayed, like that:

```twig
{% set bubble_cache = item|render %}
```

2021-05-07 10:37 UTC, imanoleguskiza submitted a review, later dismissed

2021-05-10 08:12 UTC, ademarco requested changes

2021-05-10 08:12 UTC, ademarco commented on templates/content/node--oe-person--oe-compact-teaser.html.twig
> +    {% if content.oe_person_jobs|render is not empty %}
When checking an entity reference field we can just check if the field is empty or not, not if it doesn't render anything. Checking the rendered output is not as reliable as checking the actual entity field. The node object is available in a view mode template:

![image](https://user-images.githubusercontent.com/153362/117626780-bfade000-b177-11eb-92c3-4ad3b0efcc89.png)

Simply do:

```suggestion
    {% if not node.oe_person_jobs.isEmpty() %}
```

2021-05-10 09:09 UTC, ademarco approved these changes

2021-05-10 09:10 UTC, imanoleguskiza approved these changes

2021-05-10 09:21 UTC, merged