EWPP-1104: Update drupal-driver to 2.1.0.
openeuropa/oe_theme pull request #798
Opened 2021-05-08 09:32 UTC by nagyad

2021-05-08 13:15 UTC, drishu requested changes
The patch is not ok, wrong date is shown in behat while in browser its fine

2021-05-10 11:35 UTC, drishu submitted a review, later dismissed

2021-05-18 08:53 UTC, ademarco approved these changes, later dismissed

2021-05-20 07:10 UTC, drishu approved these changes

2021-05-20 07:24 UTC, ademarco approved these changes

2021-05-20 07:30 UTC, merged