EWPP-1087: Make tables created via WYSIWYG behave correctly when disp…
openeuropa/oe_theme pull request #804
Opened 2021-05-12 12:01 UTC by yenyasinn

…layed on mobile.

2021-05-20 15:30 UTC, brummbar requested changes
Pushed a commit with a working example on how to use xpath to do all the processing.

2021-05-20 15:30 UTC, brummbar commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> +          $body->replaceChild($updated_node, $table);
I wrapped a table in a div and this line fails, as the child it's not attached to the dom body.

2021-05-20 15:30 UTC, brummbar commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> +    if (stristr($text, '<table') !== FALSE) {
Instead of having a long if(), we can have an early return when the condition is FALSE.

2021-05-20 15:30 UTC, brummbar commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> + *   type = Drupal\filter\Plugin\FilterInterface::TYPE_TRANSFORM_REVERSIBLE,
It's not reversable, because if the markup would contain already some classes instances, it wouldn't be possible to know the original status and to revert to the original markup.

2021-05-20 15:30 UTC, brummbar commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> +    $tbody_node = $table_node->getElementsByTagName('tbody')->item(0);
Tables can be imported during a migration, and might not have the tbody tag.

2021-05-20 15:30 UTC, brummbar commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> +    $thead = $table->getElementsByTagName('thead')->item(0);
Same as above, thead is optional and might not be present.

2021-05-20 15:30 UTC, brummbar commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> +  protected function isCellMerged(\DOMElement $node): bool {
We can check easily for row/colspans before doing any processing of a table by using xpath.
```
$xpath = new \DOMXPath($dom);
$span_cells = $xpath->query('.//*[self::th or self::td][(@colspan and @colspan > 1) or (@rowspan and @rowspan > 1)]', $table);
if ($span_cells->count() !== 0) {
  continue;
}
```

2021-05-20 15:30 UTC, brummbar commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> +    if (!$merged_cells && $th_exist) {
As written below , we could use Xpath once again to check that tables have a th. If none is found, we can skip the table early.

2021-05-20 15:30 UTC, brummbar commented on modules/oe_theme_helper/tests/src/Kernel/Plugin/Filter/FilterEclTableTest.php
> +    // Get FilterEclTable object.
```suggestion
    // Create an instance of the filter.
```

2021-05-20 15:30 UTC, brummbar commented on modules/oe_theme_helper/tests/src/Kernel/Plugin/Filter/FilterEclTableTest.php
> +      $this->assertStringContainsString($value, $result);
Why are we using this method instead of a simple `assertContains()`?

2021-05-20 15:30 UTC, brummbar commented on modules/oe_theme_helper/tests/src/Kernel/Plugin/Filter/FilterEclTableTest.php
> +class FilterEclTableTest extends KernelTestBase {
We don't need to use a kernel test. We are testing only the filter, so we can use a unit test like it was done for `\Drupal\Tests\oe_media_iframe\Unit\FilterIframeTagTest` (in oe_media).

2021-05-20 15:30 UTC, brummbar commented on modules/oe_theme_helper/tests/src/Kernel/Plugin/Filter/FilterEclTableTest.php
> +  protected function getTestData(): array {
Since we will convert this test to unit, we can use a real data provider. We will have the comments as keys to each test case.

2021-05-20 15:30 UTC, brummbar commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> +        if ($node->tagName === 'td') {
Why we don't add the header name for th elements?

2021-05-20 19:51 UTC, brummbar commented on modules/oe_theme_helper/src/Plugin/Filter/FilterEclTable.php
> +    $thead = $table->getElementsByTagName('thead')->item(0);
Actually thead is required in order to make the responsive styling work correctly.

2021-06-01 07:36 UTC, brummbar approved these changes
I pushed some more tests.

2021-06-01 07:36 UTC, brummbar commented on modules/oe_theme_helper/tests/src/Unit/FilterEclTableTest.php
> +      ],
Unfortunately, when treating HTML, DOMDocument doesn't care about [malformed HTML at all](https://www.php.net/manual/en/domdocument.loadhtml.php).
So this test scenario is misleading, and it can be seen as the actual html changes from the original.
We could either track parsing errors and do not process, or serialise the HTML only if changes happened. But we will do like most of the core filters do, and we re-serialise back even if no processing has occurred. Yolo.

2021-06-01 07:36 UTC, brummbar commented on modules/oe_theme_helper/tests/src/Unit/FilterEclTableTest.php
> +    $this->assertContains($expected, $processed_text);
We should actually test for exact text, so we can verify fully the work done on the HTML.

2021-06-03 12:32 UTC, nagyad approved these changes

2021-06-03 12:33 UTC, merged