EWPP-1148: Adapt site header, page header and breacrumbs to ecl V3
openeuropa/oe_theme pull request #847
Opened 2021-06-14 14:26 UTC by imanoleguskiza

## EWPP-1148

### Description

Adapt site header, page header and breacrumbs to ecl V3
### Change log

- Added:
- Changed: Adapt site header, page header and breacrumbs to ecl V3
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-06-17 15:34 UTC, sergepavle requested changes

2021-06-17 15:34 UTC, sergepavle commented on templates/patterns/page_header/pattern-page-header.html.twig
> +  'meta': metas,
I think we have to keep using 'filter_empty' filter.
```suggestion
  'meta': metas|filter_empty,
```

2021-06-17 15:34 UTC, sergepavle commented on templates/patterns/page_header/pattern-page-header.html.twig
> +  'overlay': overlay,
We have to provide this parameter only for EC ecl branding.

2021-06-17 15:34 UTC, sergepavle commented on templates/compositions/ec-component-language-list/language-list-selector.html.twig
> +  class="ecl-button ecl-button--ghost  ecl-site-header-{{ _ecl_branding }}__language-selector"
in templates/blocks/block--oe-search.html.twig classes seems like also should be updated.

2021-06-21 10:24 UTC, imanoleguskiza commented on templates/compositions/ec-component-language-list/language-list-selector.html.twig
> +  class="ecl-button ecl-button--ghost  ecl-site-header-{{ _ecl_branding }}__language-selector"
I took a look and I didn't find anything to be changed. Could you be more precise?

2021-06-21 16:10 UTC, sergepavle approved these changes, later dismissed

2021-06-22 14:36 UTC, ademarco requested changes
Page header on EU / Core looks like below: we need to make sure both text and icon are visible and that the dropdown works correctly:

![image](https://user-images.githubusercontent.com/153362/122944284-f894c380-d377-11eb-93e3-595b6014e81e.png)

On EC / Core we can have trouble seeing the text, if a picture is below it:

![image](https://user-images.githubusercontent.com/153362/122944621-44e00380-d378-11eb-94d6-77d498477437.png)

2021-06-24 12:32 UTC, imanoleguskiza commented
I pushed a fix for the colors in ec/eu flavors and to make sure nothing is invisible, but I am not sure how you propose we fix the issue with some of the text not being visibile when there is an image in the background, I feel like this is an issue editors need to take into account when uploading images.

2021-06-28 08:49 UTC, ademarco commented
I've just got new reqs that we will now have a dedicated composition for the content language switcher, so we can discard fixing it in this PR. I'll open a follow up for that only.

2021-06-28 09:08 UTC, ademarco approved these changes

2021-06-28 09:12 UTC, 22Alexandra approved these changes

2021-06-28 09:13 UTC, merged