[EWPP-1142] EWPP-1238: Fix general purpose rendering tests
openeuropa/oe_theme pull request #856
Opened 2021-06-23 08:12 UTC by 22Alexandra

2021-06-23 09:49 UTC, 22Alexandra commented
Pattern templates updates done based on the migrating information from ecl: https://github.com/ec-europa/europa-component-library/blob/v3-dev/docs/Migrating-v3.md

2021-06-24 13:59 UTC, yenyasinn approved these changes

2021-06-25 08:47 UTC, imanoleguskiza requested changes, later dismissed

2021-06-25 08:47 UTC, imanoleguskiza commented on templates/patterns/file/pattern-file.html.twig
>      'name': file.extension|to_file_icon,
There is a problem here, the "presentation" icon used in the "to_file_icon" filter is not longer available.

2021-06-25 08:51 UTC, imanoleguskiza approved these changes

2021-06-25 08:51 UTC, merged