EWPP-943: Allow using different variants of the button component for input--submit template.
openeuropa/oe_theme pull request #865
Opened 2021-06-25 12:38 UTC by 22Alexandra

2021-06-28 07:42 UTC, upchuk requested changes

2021-06-28 07:42 UTC, upchuk commented on templates/form/input--submit.html.twig
> +  variant: attributes.variant|default('primary'),
Mmmm, not really good to use the attributes array for this. That will also get printed onto the element in html.

Just make a separate variable just for that.

2021-06-28 07:44 UTC, upchuk requested changes
Also, some small test would be needed.

2021-06-28 10:59 UTC, upchuk requested changes

2021-06-28 10:59 UTC, upchuk commented on oe_theme.theme
> +  if (isset($variables['element']['#variant'])) {
Looking at the `Drupal\Core\Render\Element\Button` and it seems the element already supports a #button_type property. So we can use that instead and map it to the ECL "variant"

2021-06-29 07:02 UTC, upchuk submitted a review, later dismissed

2021-07-07 11:52 UTC, upchuk approved these changes

2021-07-07 11:55 UTC, imanoleguskiza approved these changes

2021-07-07 11:55 UTC, merged