EWPP-1280: Update list item template to fix image floating left or right.
openeuropa/oe_theme pull request #867
Opened 2021-07-01 09:30 UTC by 22Alexandra

2021-07-05 14:13 UTC, ademarco requested changes
We simply need to port the positioning classes to the new ones (in v3 `sm` becomes `s`, `md` becomes `m`, etc.).

Please start over, apply these changes, and fix tests, if necessary:

```diff
diff --git a/templates/patterns/list_item/pattern-list-item.html.twig b/templates/patterns/list_item/pattern-list-item.html.twig
index 6fcc37a8..acc382cd 100644
--- a/templates/patterns/list_item/pattern-list-item.html.twig
+++ b/templates/patterns/list_item/pattern-list-item.html.twig
@@ -21,11 +21,11 @@
      aria-label="{{ alt }}"
      class="ecl-u-ratio-3-2
       ecl-u-flex-shrink-0
-      ecl-u-d-lg-block
+      ecl-u-d-l-block
       ecl-content-item__image__{{ position }}
-      ecl-u-{{ position == 'before' ? 'mr' : 'ml' }}-sm-l
+      ecl-u-{{ position == 'before' ? 'mr' : 'ml' }}-s-l
       ecl-u-{{ position == 'before' ? 'mb' : 'mt' }}-l
-      ecl-u-{{ position == 'before' ? 'mb' : 'mt' }}-sm-none"
+      ecl-u-{{ position == 'before' ? 'mb' : 'mt' }}-s-none"
      style="background-image: url('{{ src }}');
        background-size: contain;
        background-position: center;
@@ -35,7 +35,7 @@
 ></div>
 {% endmacro %}
 
-<article class="ecl-content-item ecl-u-d-sm-flex ecl-u-pb-m">
+<article class="ecl-content-item ecl-u-d-s-flex ecl-u-pb-m">
   {% if image and image_position == 'before' %}
     {{ _self.image(image.src, image.alt, image_position) }}
   {% endif %}
```

2021-07-06 09:03 UTC, ademarco approved these changes, later dismissed

2021-07-06 09:39 UTC, ademarco approved these changes

2021-07-06 14:12 UTC, imanoleguskiza approved these changes

2021-07-06 14:12 UTC, merged