EWPP-1289: Add missing interface translations.
openeuropa/oe_theme pull request #874
Opened 2021-07-08 08:07 UTC by yenyasinn

2021-07-16 10:10 UTC, nagyad requested changes

2021-07-16 10:10 UTC, nagyad commented on modules/oe_theme_helper/translations/oe_theme_helper-hr.po
> +msgstr ""
Why are we removing this to an empty string?

2021-07-16 10:10 UTC, nagyad commented on modules/oe_theme_helper/translations/oe_theme_helper-hu.po
> +msgstr ""
Why are we removing this?

2021-07-16 10:10 UTC, nagyad commented on modules/oe_theme_helper/translations/oe_theme_helper-lv.po
> +msgstr ""
Why to change to an empty string?

2021-07-19 07:15 UTC, nagyad submitted a review, later dismissed

2021-07-20 14:16 UTC, sergepavle commented on modules/oe_theme_content_call_proposals/templates/oe_theme_content_call_proposals_publication_info.html.twig
> +{{ date }}{% if link is not empty %}{% trans ' in' with {'context': 'Call for proposals'} %}
The current solution is working but why can't use this approach: `{{ '@date in @journal'|t({'@date': date, '@journal': link }) }}`

2021-07-20 14:16 UTC, sergepavle commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
>  msgid "Registration period ended on @date."
We have an issue with translation because the original string is without the dot.
```
      $build['#description'] = $this->t('Registration period ended on @date', [
        '@date' => $this->dateFormatter->format($datetime_end->getTimestamp(), 'oe_event_long_date_hour'),
      ]);
```

2021-07-20 14:16 UTC, sergepavle commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Topic"
Where is this string used for translation in frontend?

2021-07-20 14:16 UTC, sergepavle commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Languages"
Where is this string used for translation in frontend?

2021-07-20 14:16 UTC, sergepavle commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Keywords"
Where is this string used for translation in frontend?

2021-07-20 14:16 UTC, sergepavle commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "No results have been found"
Where is this string used for translation in frontend?

2021-07-20 14:16 UTC, sergepavle commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Before"
Where is this string used for translation in frontend?

2021-07-20 14:16 UTC, sergepavle commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "In between"
Where is this string used for translation in frontend?

2021-07-20 14:16 UTC, sergepavle commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Upcoming and ongoing"
Where is this string used for translation in frontend?

2021-07-20 14:16 UTC, sergepavle commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Past"
Where is this string used for translation in frontend?

2021-07-20 15:46 UTC, yenyasinn commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Keywords"
On the Pool page
<img width="1190" alt="Screenshot 2021-07-20 at 18 18 53" src="https://user-images.githubusercontent.com/1183951/126350350-8808afa8-bc6c-4441-aa0d-30cfed01578f.png">

2021-07-20 15:46 UTC, yenyasinn commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "No results have been found"
On the Pool page
<img width="1155" alt="Screenshot 2021-07-20 at 18 20 12" src="https://user-images.githubusercontent.com/1183951/126350574-d6cc6a67-9308-4900-af71-e4f7727068ff.png">

2021-07-20 15:46 UTC, yenyasinn commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Before"
On the Pool page
<img width="1194" alt="Screenshot 2021-07-20 at 18 21 32" src="https://user-images.githubusercontent.com/1183951/126350836-ca73f4ef-dae4-483e-80c3-fb8b6533c6fc.png">

2021-07-20 15:46 UTC, yenyasinn commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "In between"
On the Pool page
<img width="1194" alt="Screenshot 2021-07-20 at 18 21 32" src="https://user-images.githubusercontent.com/1183951/126350836-ca73f4ef-dae4-483e-80c3-fb8b6533c6fc.png">

2021-07-20 15:46 UTC, yenyasinn commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Upcoming and ongoing"
On the pool page
<img width="1168" alt="Screenshot 2021-07-20 at 18 42 36" src="https://user-images.githubusercontent.com/1183951/126354305-23315e0d-b7ad-4a87-aea9-63c05cb0cb80.png">

2021-07-20 15:46 UTC, yenyasinn commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Past"
On the pool page
<img width="1168" alt="Screenshot 2021-07-20 at 18 42 36" src="https://user-images.githubusercontent.com/1183951/126354305-23315e0d-b7ad-4a87-aea9-63c05cb0cb80.png">

2021-07-20 15:46 UTC, yenyasinn commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Topic"
On the Contact form
<img width="577" alt="Screenshot 2021-07-20 at 18 45 39" src="https://user-images.githubusercontent.com/1183951/126354820-5a69a238-8858-424a-bc4d-0548d33c29f0.png">

2021-07-20 15:53 UTC, yenyasinn commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Languages"
On the Event page
<img width="827" alt="Screenshot 2021-07-20 at 18 51 57" src="https://user-images.githubusercontent.com/1183951/126355774-733def02-4e42-49f7-9768-91628da5c7b7.png">

2021-07-22 14:57 UTC, sergepavle commented on modules/oe_theme_helper/translations/oe_theme_helper-bg.po
> +msgid "Topic"
Sorry, my bad. Seems like phpstorm doesn't have a reliable search.

2021-07-22 14:58 UTC, sergepavle submitted a review, later dismissed

2021-07-22 14:59 UTC, nagyad approved these changes, later dismissed

2021-08-12 08:07 UTC, yenyasinn commented
It was merged into 3.x

2021-08-12 08:07 UTC, closed without merging