EWPP-1367: Add related departments field to news.
openeuropa/oe_theme pull request #910
Opened 2021-08-06 09:45 UTC by nagyad

2021-08-08 16:31 UTC, 22Alexandra requested changes

2021-08-08 16:31 UTC, 22Alexandra commented on modules/oe_theme_content_news/oe_theme_content_news.module
> +      'oe_departments' => t('Related departments'),
In the [requirements page](https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=572200293), the label is "Departments".

2021-08-08 16:31 UTC, 22Alexandra commented on templates/field/field--node--oe-departments--oe-news--full.html.twig
> + * Theme override for the Responsible department field template of the News content type.
```suggestion
 * Theme override for the Related department field template of the News content type.
```

2021-08-08 16:31 UTC, 22Alexandra commented on modules/oe_theme_content_news/config/install/core.entity_view_display.node.oe_news.full.yml
> -    - datetime
Why?

2021-08-09 07:34 UTC, nagyad commented on modules/oe_theme_content_news/config/install/core.entity_view_display.node.oe_news.full.yml
> -    - datetime
It was automatic.

2021-08-09 07:35 UTC, nagyad commented on modules/oe_theme_content_news/oe_theme_content_news.module
> +      'oe_departments' => t('Related departments'),
Yeah but as I explained in a comment of the ticket I followed our pattern of handling prular and singular labels

2021-08-09 08:57 UTC, 22Alexandra commented on modules/oe_theme_content_news/oe_theme_content_news.module
> +      'oe_departments' => t('Related departments'),
My remark is about the label itself that should be "Department" for singular and "Departments" for plural, not the implementation.

2021-08-09 11:41 UTC, 22Alexandra submitted a review, later dismissed

2021-08-11 09:43 UTC, sergepavle submitted a review, later dismissed

2021-08-11 12:26 UTC, 22Alexandra approved these changes

2021-08-11 12:37 UTC, sergepavle approved these changes

2021-08-11 12:48 UTC, sergepavle approved these changes

2021-08-11 14:56 UTC, merged