EWPP-1409: Change string in language switcher.
openeuropa/oe_theme pull request #915
Opened 2021-08-10 10:59 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-08-10 12:40 UTC, 22Alexandra requested changes
Can we add test coverage for the message within this class `ContentLanguageSwitcherTest`?

2021-08-10 13:41 UTC, 22Alexandra approved these changes, later dismissed

2021-08-10 14:54 UTC, nagyad approved these changes, later dismissed

2021-08-12 08:21 UTC, 22Alexandra approved these changes

2021-08-12 08:22 UTC, nagyad approved these changes

2021-08-12 08:29 UTC, merged