EWPP-873: Text with featured media paragraph type V2
openeuropa/oe_theme pull request #939
Opened 2021-09-07 10:20 UTC by yenyasinn

2021-09-08 07:02 UTC, ademarco requested changes

2021-09-08 07:02 UTC, ademarco commented on modules/oe_theme_helper/oe_theme_helper.post_update.php
> +function oe_theme_helper_post_update_20017() {
This is now ran by oe_paragraphs, we should remove it from here. Same goes for the configuration file itself.

2021-09-08 07:02 UTC, ademarco commented on oe_theme.theme
> +      'label' => $link_field->get('title')->getValue(),
Is link field cache properly bubbled here?

2021-09-17 11:01 UTC, sergepavle submitted a review, later dismissed

2021-09-17 12:02 UTC, upchuk approved these changes

2021-09-17 12:14 UTC, ademarco approved these changes

2021-09-17 12:42 UTC, merged