EWPP-756: Add highlighted label to nodes teaser view mode.
openeuropa/oe_theme pull request #955
Opened 2021-09-23 14:03 UTC by 22Alexandra

2021-10-04 12:14 UTC, imanoleguskiza requested changes

2021-10-04 12:14 UTC, imanoleguskiza commented on package.json
> +    "@ecl/twig-component-label": "3.0.2",
Since we added the label component here, I think we should update the oe-theme-helper-call-label-status.html.twig to use it instead of hardcoding it.

2021-10-04 12:14 UTC, imanoleguskiza commented on templates/patterns/list_item/pattern-list-item--variant-date.html.twig
> +            <br>
I don't think this is needed? I tried without it and it seemed to work fine.

2021-10-04 12:14 UTC, imanoleguskiza commented on templates/patterns/list_item/pattern-list-item--variant-date.html.twig
> +            <span id="status">
I would not use an ID here, better if we add a class like "ecl-content-item-date__status" or smth

2021-10-11 12:44 UTC, imanoleguskiza commented on modules/oe_theme_content_news/oe_theme_content_news.module
> +  $node = $variables['node'];
Maybe we could add the sticky in all nodes so we avoid repeating the same thing over and over.

2021-10-13 13:06 UTC, nagyad requested changes
Rest looks good.

2021-10-13 13:06 UTC, nagyad commented on modules/oe_theme_content_call_proposals/oe_theme_content_call_proposals.module
> +    }
Switch case please.

2021-10-13 13:06 UTC, nagyad commented on modules/oe_theme_content_call_tenders/oe_theme_content_call_tenders.module
> +    }
Switch case please.

2021-10-13 13:06 UTC, nagyad commented on modules/oe_theme_content_consultation/oe_theme_content_consultation.module
> +    }
Switch case please.

2021-10-18 08:10 UTC, imanoleguskiza submitted a review, later dismissed

2021-10-18 08:25 UTC, nagyad submitted a review, later dismissed

2021-10-26 10:25 UTC, imanoleguskiza approved these changes

2021-10-26 10:52 UTC, nagyad approved these changes

2021-10-26 10:55 UTC, merged