EWPP-1557: Translate "@date in" to Arabic and Turkish languages.
openeuropa/oe_theme pull request #958
Opened 2021-09-24 15:26 UTC by yenyasinn

2021-10-04 10:41 UTC, 22Alexandra requested changes

2021-10-04 10:41 UTC, 22Alexandra commented on modules/oe_theme_helper/tests/src/Kernel/TwigExtensionTest.php
> +
This can be removed.

2021-10-04 10:41 UTC, 22Alexandra commented on modules/oe_theme_helper/tests/src/Kernel/TwigExtensionTest.php
> +    $result = $this->renderElements($render_string);
Replace with `\Drupal\Tests\oe_theme\Traits\RenderTrait::renderRoot`. The `RenderTrait` just needs to be used within the class.

2021-10-04 10:41 UTC, 22Alexandra commented on tests/Functional/ContentCallForProposalsRenderTest.php
> +    $details_expected_values['items'][2]['body'] = "12 February 2020 in Official Journal Reference";
Could we test the translation works properly in `\Drupal\Tests\oe_theme\Kernel\CallForProposalsRenderTest::testTeaser` the same as we test for Event (`\Drupal\Tests\oe_theme\Kernel\EventRenderTest::testEventTeaser`)?

2021-10-05 09:59 UTC, 22Alexandra commented on tests/Functional/ContentCallForProposalsRenderTest.php
> +    $details_expected_values['items'][2]['body'] = "12 February 2020 in Official Journal Reference";
My bad, the string is not rendered in the Teaser.

2021-10-05 10:00 UTC, yenyasinn commented on modules/oe_theme_helper/tests/src/Kernel/TwigExtensionTest.php
> +    $result = $this->renderElements($render_string);
Yes, it can be simplified.

2021-10-05 15:33 UTC, 22Alexandra approved these changes, later dismissed

2021-10-05 17:09 UTC, brummbar requested changes
Blocking for review on me

2021-10-13 07:10 UTC, brummbar requested changes

2021-10-13 07:10 UTC, brummbar commented on modules/oe_theme_helper/tests/src/Kernel/TwigExtensionTest.php
> +    // Twig doesn't escape Markup object.
```suggestion
    // Twig doesn't escape Markup objects.
```

2021-10-13 07:10 UTC, brummbar commented on modules/oe_theme_helper/tests/src/Kernel/TwigExtensionTest.php
> +    // Twig escapes strings from the variable by default.
```suggestion
    // Twig escapes string variables by default.
```

2021-10-13 07:10 UTC, brummbar commented on modules/oe_theme_helper/tests/src/Kernel/TwigExtensionTest.php
> +  public function testCreateMarkup() {
This test doesn't need Drupal to be bootstrapped, and it could be written as unit test in `/modules/oe_theme_helper/tests/src/Unit/TwigExtensionTest.php`.
We can test that the filter returns a markup object by doing `$this->extension->createMarkup()` too, aside from doing a render test.

2021-10-21 15:03 UTC, brummbar approved these changes, later dismissed

2021-10-22 11:06 UTC, nagyad submitted a review, later dismissed

2021-11-10 07:12 UTC, upchuk approved these changes

2021-11-10 07:46 UTC, merged