EWPP-1575:  Move oe_theme_content_* modules out to its own project.
openeuropa/oe_theme pull request #962
Opened 2021-09-28 08:37 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-10-12 12:40 UTC, nagyad requested changes

2021-10-12 12:40 UTC, nagyad commented on README.md
> +In 2.21.0 we moved all existing companion submodules related to content theming in a separate project `oe_theme_content`.
Here the version should be 3.1.0, no?

2021-10-12 13:06 UTC, sergepavle commented on README.md
> +In 2.21.0 we moved all existing companion submodules related to content theming in a separate project `oe_theme_content`.
Should be 3.1.0 but can be another.

2021-10-14 08:35 UTC, ademarco commented
Closing as won't fix.

2021-10-14 08:35 UTC, closed without merging