EWPP-685: Image caption and copyright not showing
openeuropa/oe_theme pull request #967
Opened 2021-10-21 10:24 UTC by yenyasinn

2021-10-25 11:40 UTC, nagyad requested changes

2021-10-25 11:40 UTC, nagyad commented on modules/oe_theme_helper/oe_theme_helper.module
> +  }
In the else you do the same, I think you can restructure this if to avoid code duplication plus I'm not sure we really need the 2 ifs for image style cases.

2021-10-26 11:39 UTC, nagyad submitted a review, later dismissed

2021-11-09 12:29 UTC, sergepavle submitted a review, later dismissed

2021-11-11 12:52 UTC, sergepavle approved these changes, later dismissed

2021-11-30 10:24 UTC, sergepavle approved these changes

2021-11-30 16:19 UTC, nagyad approved these changes

2021-12-02 11:48 UTC, merged