EWPP-1609: Add badges paramater to list_item and featured_item patterns.
openeuropa/oe_theme pull request #973
Opened 2021-10-26 13:39 UTC by 22Alexandra

2021-11-22 16:58 UTC, imanoleguskiza requested changes

2021-11-22 16:58 UTC, imanoleguskiza commented on templates/patterns/file_translation/pattern-file-translation.html.twig
> +  'variant': 'thumbnail',
The problem here is that this is not "backwards compatible", in the sense that if someone is using this pattern and does not add a thumbnail will get nothing. I propose we check whether we have a thumbnail or not and set the variant accordingly? cc @ademarco

2021-11-23 09:26 UTC, imanoleguskiza commented on templates/patterns/file_translation/file_translation.ui_patterns.yml
> +    highlighted:
We agreed with @ademarco we won't add this style of property and instead we will use the same "Badges" approach as we use in other patterns

2021-11-26 10:38 UTC, imanoleguskiza approved these changes, later dismissed

2021-11-30 15:40 UTC, imanoleguskiza approved these changes

2021-12-03 08:54 UTC, ademarco approved these changes

2021-12-03 08:54 UTC, merged