EWPP-1630: Add lists property to file-teaser.
openeuropa/oe_theme pull request #974
Opened 2021-10-27 12:54 UTC by nagyad

2021-11-03 11:03 UTC, 22Alexandra reviewed
The build is failing.

2021-11-03 11:56 UTC, nagyad commented
Waiting for this PR to be merged. https://github.com/openeuropa/oe_theme/pull/976

2021-11-08 07:57 UTC, imanoleguskiza requested changes, later dismissed

2021-11-08 07:57 UTC, imanoleguskiza commented on tests/Kernel/fixtures/rendering.yml
> +      'span.ecl-description-list__tag': 2
I wonder if we should also check the contents of the tags and the terms

2021-11-10 08:05 UTC, 22Alexandra approved these changes, later dismissed

2021-11-11 15:12 UTC, 22Alexandra approved these changes

2021-11-11 15:13 UTC, upchuk approved these changes
For imanol.

2021-11-11 15:14 UTC, merged