[EWPP-1539] EWPP-1756: Theming of Event Speaker field.
openeuropa/oe_theme pull request #988
Opened 2021-11-23 17:17 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-11-24 13:31 UTC, 22Alexandra commented on tests/src/Functional/ContentEventRenderTest.php
> +
Could document the code a bit.

2021-11-24 13:32 UTC, 22Alexandra submitted a review, later dismissed

2021-11-24 15:03 UTC, nagyad requested changes

2021-11-24 15:03 UTC, nagyad commented on oe_theme.theme
> +    // Set portrait image URL.
Remove this empty line

2021-11-24 15:03 UTC, nagyad commented on oe_theme.theme
> +      $renderable = $node_view_builder->viewField($person->get('oe_person_photo'), [
Variable name is too ambiguous.

2021-11-24 15:03 UTC, nagyad commented on oe_theme.theme
> +      $item['content']['portrait_image']['#markup'] = base_path() . drupal_get_path('theme', 'oe_theme') . '/images/user_icon.svg';
Normally we have a helper function to retrieve person image, no? If not shall we use one that incorporates these logic?

2021-11-24 15:03 UTC, nagyad commented on templates/field/field--entity-reference-revisions--oe-event-speaker.html.twig
> +<h2 class="ecl-u-type-heading-2 ecl-u-mt-2xl ecl-u-mt-m-3xl ecl-u-mb-l">{{ label }}</h2>
I think we should use spaceless in this template.

2021-11-24 15:03 UTC, nagyad commented on tests/src/Functional/ContentEventRenderTest.php
> +    $this->assertEquals($person->label(), $link->getText());
I noticed that the person name is capitalized.
![image](https://user-images.githubusercontent.com/22004498/143262492-0eb4e5ef-6813-4fc0-8681-20bf6fa2a2e0.png)

2021-11-25 08:36 UTC, sergepavle commented on oe_theme.theme
> +      $item['content']['portrait_image']['#markup'] = base_path() . drupal_get_path('theme', 'oe_theme') . '/images/user_icon.svg';
Good point. I've reworked the existing helper function.

2021-11-25 12:17 UTC, nagyad requested changes

2021-11-25 12:17 UTC, nagyad commented on templates/field/field--entity-reference-revisions--oe-event-speaker.html.twig
> +{% spaceless %}
Move this above the `<h2>` line.

2021-11-25 12:20 UTC, nagyad approved these changes

2021-11-26 08:07 UTC, 22Alexandra approved these changes

2021-11-26 11:08 UTC, merged