EWPP-1803: Theme extra fields.
openeuropa/oe_theme pull request #995
Opened 2021-12-02 17:18 UTC by 22Alexandra

2021-12-06 08:01 UTC, imanoleguskiza requested changes

2021-12-06 08:01 UTC, imanoleguskiza commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/LocationExtraField.php
> +        return [];
We are losing the cache metatags here, if a user gets access at a later stage they cache won't be validated. I'm wondering, the view builder does not check the access when rendering?

2021-12-06 08:01 UTC, imanoleguskiza commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/MediaExtraField.php
> +      return [];
We need to return the build, otherwise we lose the tags

2021-12-06 08:01 UTC, imanoleguskiza commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/MediaExtraField.php
> +      return [];
Same here, careful with tags

2021-12-06 10:42 UTC, 22Alexandra commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/LocationExtraField.php
> +        return [];
It won't check the access.

2021-12-12 19:10 UTC, imanoleguskiza submitted a review, later dismissed

2022-01-03 12:03 UTC, nagyad requested changes

2022-01-03 12:03 UTC, nagyad commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/MediaExtraField.php
> +      $this->isEmpty = TRUE;
![image](https://user-images.githubusercontent.com/22004498/147928245-6346edea-146a-41d3-a9a1-ab342e079824.png)
I didn't fill any of these fields in.

2022-01-03 12:05 UTC, nagyad commented on modules/oe_theme_content_event/src/Plugin/ExtraField/Display/MediaExtraField.php
> +      $this->isEmpty = TRUE;
When I fill it in, I get double titles.
![image](https://user-images.githubusercontent.com/22004498/147928483-ca29417f-7e1c-40b6-9fe1-e9320908654d.png)

2022-01-03 15:53 UTC, nagyad approved these changes, later dismissed

2022-01-04 09:44 UTC, imanoleguskiza submitted a review, later dismissed

2022-01-05 11:42 UTC, upchuk approved these changes
blind for imanol

2022-01-05 11:42 UTC, nagyad approved these changes

2022-01-05 11:43 UTC, merged